### PR TITLE
Revert #1658

### PR DESCRIPTION
**Pull request by ValarDragon**
## What is the purpose of the change

#1658 broke `make proto-all` on my machine. Is there something I need to do update the containers? Could others check if it still works for them on main?

## Testing and Verifying

Checkout the branch, make a proto comment change and try `make proto-all`. Check that a difference is generated

### CODE REVIEW

**Comment by mattverse** [comment]
hrrm `make proto-all` seems to work for me atm(getting few warnings on nullable options in the process but still works)

**Comment by mattverse** [comment]
What's the error you get when you run `make proto-all`?

**Comment by robert-zaremba** [comment]
hmm, it was working fine for me. Could you share the error message?

**Comment by ValarDragon** [comment]
I don't get an error, the make commands just don't do anything. They print some lines, but don't generate any code. I tried editing comments in proto files, and `make proto-gen` and `make proto-all` would act as no-ops.

Changing this back to `osmosis` gets the commands to execute for me.

**Comment by robert-zaremba** [comment]
I've tested on `main` and it worked without a problems:
+ added few comments 
+ run `make proto-all`
+ go files were updated - see attached diff
[proto-check.txt](https://github.com/osmosis-labs/osmosis/files/8848082/proto-check.txt)

**Comment by robert-zaremba** [comment]
I think the problem @ValarDragon has is with some conflict - you probably were testing some versions and didn't delete it. It happens sometimes no matter which image you are using. Could you remove your running containers? Eg: `docker system prune`

**Comment by ValarDragon** [comment]
Ah your spot on @robert-zaremba ! Thank you! This fixed it for me =)

**Pull request closed without merging**
