### PR TITLE
Revert fixed gas cost

### PR DESCRIPTION
**Pull request by hieuvubk**
Closes: #2758

## What is the purpose of the change

*Refer from #2758,  remove `BalancerGasFeeForSwap` constant & refact related test*

### CODE REVIEW

**Comment by hieuvubk** [comment]
got CI check failed even I don't touch this file
Ảnh chụp Màn hình 2022-09-20 lúc 10 19 57

**Comment by mattverse** [comment]
we currently have a bug in the CI, re-running it passes the check

**Review by mattverse — COMMENTED** [review]
Confirmed that this PR only reverts changes made from #2016 

We want the base branch to be against V12 right? Or do we want to completely remove it from main? I feel like reverting it on v12 would suffice?

cc. @czarcas7ic

**Comment by mattverse** [comment]
yeah can we switch the base branch to v12.x @hieuvubk ?

**Comment by p0mvn** [comment]
@hieuvubk looks like you might have to take cherry-pick your commits on top of `v12.x`

**Comment by hieuvubk** [comment]
> @hieuvubk looks like you might have to take cherry-pick your commits on top of `v12.x`

Yes I'll create new pr base on v.12.x. This pr based on main so got many conflict

**Comment by hieuvubk** [comment]
@mattverse @p0mvn could you pls check pr #2808

**Comment by mattverse** [comment]
Closing this PR, as a new PR was opened against v12.x, and we don't want to revert gas cost PR from main

**Pull request closed without merging**
