### PR TITLE
x/gamm: Add check for correct input asset denoms to CalcJoinPoolShares

### PR DESCRIPTION
**Pull request by AlpinYukseloglu**
Closes: #1906 

## What is the purpose of the change

Our current implementation of CalcJoinPoolShares checks to make sure the _number_ of denoms sent in for an all-asset join is correct, but has no check for whether those assets are actually the correct denoms. This makes it so that entirely invalid inputs (i.e. correct number of input tokens but incorrect denoms) successfully make it through the entire set of all-asset join calculations until they are incidentally caught in the single-asset join section due to a check in `updateIntermediaryPoolAssetsLiquidity`.

https://github.com/osmosis-labs/osmosis/blob/85529c76683f2d2f2ffb2121125baf0e39463f84/x/gamm/pool-models/balancer/amm.go#L368-L370

This PR adds an additional check to the input tokens that makes sure they are of the correct denoms so that the function never assumes invalid inputs are correct for calculating all-asset joins.

## Brief Changelog

- Adds a check similar to `DenomsSubsetOf` that makes sure that the input denoms are part of the pool being joined (Note: we cannot use `DenomsSubsetOf` here because we have a denom->PoolAsset map instead of a set of `sdk.Coins` to represent pool liquidity)

## Testing and Verifying

This change is already covered by existing GAMM tests.

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (no)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (no)
  - How is the feature or change documented? (not applicable)

### CODE REVIEW

**Review by mattverse — APPROVED** [review]
I do think that the existing code base does have checks within the methods of `CalcJoinPoolShares` already, but Im generally agreeing on this extra explicit sanity check!

**Review by alexanderbez — APPROVED** [review]
LGTM

1. Do we have a test case already testing this path? If not, we should definitely add one.
2. We should get a changelog entry in.

**Comment by AlpinYukseloglu** [comment]
> LGTM
> 
> 1. Do we have a test case already testing this path? If not, we should definitely add one.

I believe this test should cover it but happy to add another one with more assets/mixed assets if you think it would be useful:
https://github.com/osmosis-labs/osmosis/blob/2007babdee01e9bb7743ccadeff097cdab9b7236/x/gamm/pool-models/balancer/pool_test.go#L121

> 2. We should get a changelog entry in.

Added in recent commit!

**Comment by p0mvn** [comment]
> > LGTM
> > 
> > 1. Do we have a test case already testing this path? If not, we should definitely add one.
> 
> I believe this test should cover it but happy to add another one with more assets/mixed assets if you think it would be useful:
> 
> https://github.com/osmosis-labs/osmosis/blob/2007babdee01e9bb7743ccadeff097cdab9b7236/x/gamm/pool-models/balancer/pool_test.go#L121
> 
> > 2. We should get a changelog entry in.
> 
> Added in recent commit!

Just making sure we don't miss anything - was that commit pushed? Not seeing a new test

**Review by p0mvn — APPROVED** [review]
LGTM

**Comment by AlpinYukseloglu** [comment]
> Just making sure we don't miss anything - was that commit pushed? Not seeing a new test

This test was already there so it's not a part of this PR. The link I included was directly from main

**Review by alexanderbez — APPROVED** [review]

**Pull request merged**
