### PR TITLE
Accumulation store reset on lockup migration

### PR DESCRIPTION
**Pull request by mconcat**
changes made other than the main migration script:
- remove Lock() as an exported method for locking tokens
- use LockTokens() for single entry point for locking tokens
- add createLock() that creates a lock with next lock ID
- createLock() and deleteLock() now add/deletes lockrefs in it 

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by ValarDragon** [comment]
These are great API changes, that I also thought were problematic as I was reviewing the lockref code yesterday

**Comment by ValarDragon** [comment]
RIP the merge conflicts. I do think the API changes this PR did  + a function to reset the accumulation store during a migration are both really useful things we still want to get in.

I think the move to proceed here may be to re-PR the API changes as one PR, and re-PR the migration logic, due to the merge conflicts.

**Comment by alexanderbez** [comment]
> I think the move to proceed here may be to re-PR the API changes as one PR, and re-PR the migration logic, due to the merge conflicts.

I totally agree. @mconcat do you want help here?

**Comment by mconcat** [comment]
Yeah I will, re-PR seems more reasonable

**Pull request closed without merging**
