### PR TITLE
feat(math): add mutative api for BigDec.BigInt() 

### PR DESCRIPTION
**Pull request by DongLieu**
Similar to https://github.com/cosmos/cosmos-sdk/pull/17803 I think we should also have such an API

### CODE REVIEW

**Review by mattverse — APPROVED** [review]
LGTM

**Comment by mattverse** [comment]
@DongLieu Can you add changelog entry for this?

**Comment by mattverse** [comment]
Leaving this 1 more day to see if anyone wants extra review, merging this in trmw

**Comment by DongLieu** [comment]
Ok, thanks you

**Pull request merged**
