### PR TITLE
add latest buf generation

### PR DESCRIPTION
**Pull request by nghuyenthevinh2000**
Closes: #XXX

Protobuf generation with buf has gone a long way.

buf latest version: 1.4.0 has deleted "buf protoc".

the last version of buf that still supports "buf protoc" is: https://github.com/bufbuild/buf/releases/tag/v1.0.0-rc12

this creates frustration for engineers using latest version of buf since they will have to first figure out why "buf protoc" is gone when running ancient protocgen.sh

this pr intends to upgrade osmosis proto generation to latest with benefits:
1. no more complex proto generation script
2. using more clear buf.yaml structure
3. up - to - date buf binary with "buf protoc" removed
4. leverage "Buf Schema Registry" to include cosmos-sdk, cosmos-proto, googleapis proto files remotely in generating osmosis proto

> Add a description of the overall background and high level changes that this PR introduces

*(E.g.: This pull request improves documation of area A by adding ....*

## Brief Changelog

*(for example:)*
 
  - *The metadata is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *Daemons retrieve the RPC data from the blob cache*

## Testing and Verifying

*(Please pick one of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added unit test that validates ...*
  - *Added integration tests for end-to-end deployment with ...*
  - *Extended integration test for ...*
  - *Manually verified the change by ...*

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (yes / no)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (yes / no)
  - How is the feature or change documented? (not applicable   /   specification (`x/<module>/spec/`)  /  [Osmosis docs repo](https://github.com/osmosis-labs/docs)   /   not documented)

### CODE REVIEW

**Comment by nghuyenthevinh2000** [comment]
currently, it faces a weird problem of: interfacetype only supports messages with exactly one oneof declaration

here is where the error comes from:

https://github.com/regen-network/cosmos-proto/blob/master/interfacetype/interfacetype.go#L56

**Comment by ValarDragon** [comment]
Is this different then whats going on in #1589

**Comment by faddat** [comment]
hi :) I thinik that you **might** be able to use cosmos-proto to resolve this.  Maybe that's a 46 thing though?

**Comment by nghuyenthevinh2000** [comment]
oh, it is the same, I will move over that issue

**Comment by nghuyenthevinh2000** [comment]
@alexanderbez ser, can you check over .yaml files that I have written here as well as new_protocgen.sh

the code is running

**Comment by nghuyenthevinh2000** [comment]
> @nghuyenthevinh2000 how does this differ from my PR? I'd rather merge my PR (removing pulsar/ORM stuff) as it's a direct drop-in from the SDK.

1. Firstly, I want to say that I understand your feelings.
2. Secondly, direct from the SDK is not fit to Osmosis. I wil explain why:

- buf.gen.gogo.yaml lacks protoc-gen-doc which is needed to generate proto-docs.md. Through my experience and understanding of buf.gen.yaml, I have added protoc-gen-doc to buf.gen.yaml with strategy "all". This is not present in buf.gen.gogo.yaml of the SDK.
- My customization also consider "make proto-gen". tendermintdev/sdk-proto-gen:v0.2 docker image has only old buf which doesn't have "buf mod". Therefore, I have to locate the correct image that supports higher buf version and find out that tendermintdev/sdk-proto-gen:v0.3 docker is the only one that fits. v0.4 and above seems to have removed protoc-gen-doc.
- Understanding of buf.gen.yaml "strategy" has allowed me to write significantly shorter and easier to read protocgen.sh

**Comment by alexanderbez** [comment]
I'm not sure I follow? Proto docs were and still are generated via `make proto-gen`.

**Comment by ValarDragon** [comment]
I am in favor of only doing this upgrade when we switch to an SDK version that does it as well / changing things upstream in the SDK.

I would everything around build process / proto generation to be as standard as possible, despite costs this may induce relative to the ideal. Maintaining alternate protobuf generation doesn't seem like a great reward vs maintenance payoff.

I currently build proto-docs via `make proto-all` and whatever thats doing internally.

Thanks for the interest in changing things here! I'd personally prefer closing this though / making isolated issues / PR's for discussing further problems we may be having / if theres a setup problem your having.

**Comment by nghuyenthevinh2000** [comment]
> I am in favor of only doing this upgrade when we switch to an SDK version that does it as well / changing things upstream in the SDK.
> 
> I would like everything around build process / proto generation to be as standard as possible, despite costs this may induce relative to the ideal. Maintaining alternate protobuf generation doesn't seem like a great reward vs maintenance payoff to me.
> 
> I currently build proto-docs via `make proto-all` and whatever thats doing internally.
> 
> Thanks for the interest in changing things here! I'd personally prefer closing this though / making isolated issues / PR's for discussing further problems we may be having / if theres a setup problem your having.

love to hear opinions. I will close this one for further discussion.

**Pull request closed without merging**
