### PR TITLE
fix: update wasm vm as per CWA-2023-004

### PR DESCRIPTION
**Pull request by czarcas7ic**
Closes: #XXX

## What is the purpose of the change

As per CWA-2023-004, bump wasmvm version from v1.5.0 to v1.5.1

### CODE REVIEW

**Comment by czarcas7ic** [comment]
This update has failed e2e 3 times in a row

**Review by PaddyMc — APPROVED** [review]

**Comment by mattverse** [comment]
Double checked, this is the only PR that's making e2e fail rn 🤔

**Comment by PaddyMc** [comment]
e2e tests passed after being re-run :smiling_face_with_tear:

**Comment by mattverse** [comment]
@PaddyMc Yep, but super flaky. I've ran it multiple times myself, but fails at the same point

**Comment by czarcas7ic** [comment]
Going to merge the E2E change and then merge that into this PR and determine if we were just unlucky or if this PR actually makes a change that modifies logic negatively

**Review by p0mvn — APPROVED** [review]

**Pull request merged**
