### PR TITLE
chore: go 1.19 for ci only and cleanup

### PR DESCRIPTION
**Pull request by faddat**
## What is the purpose of the change

Go 1.19 adds some new cryptographic safety features.

https://tip.golang.org/doc/go1.19

## Brief Changelog

* golangci-lint run ./... --fix
* replace ioutil
* update docker and ci to go 1.19
* update dependabot so that it covers github actions too.  Many of ours are out of date. 

## Testing and Verifying

make test should pass, and this should pass all ci checks.  It doesn't change functionality. 

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? no
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? yes
  - How is the feature or change documented? NA

### CODE REVIEW

**Comment by faddat** [comment]
The proto docker image should be updated later today.

I noticed we're using super-linter-- fyi we dropped that from pylons; it kept giving us pretty poor results.

**Comment by p0mvn** [comment]
> The proto docker image should be updated later today.
> 
> I noticed we're using super-linter-- fyi we dropped that from pylons; it kept giving us pretty poor results.

thanks @faddat . super-linter is only used for linting markdowns, everything else is disabled

**Comment by ValarDragon** [comment]
Lets not update to go 1.19 immediately, I don't see much utility in forcing everyone to update their golang versions immediately

**Comment by faddat** [comment]
@ValarDragon wasn't figuring that this should be immediate (backported) -- instead was figuring a next release thing. 

Close?

**Comment by faddat** [comment]
I figure that this approach is better.

**Comment by ValarDragon** [comment]
These lint changes + CI changes differ from other osmosis standards (e.g. CI YML)

Going to close this for now

**Pull request closed without merging**
