### PR TITLE
fix dependencies for merged commit of the cosmos-sdk fork

### PR DESCRIPTION
**Pull request by nicolaslara**
This replaces #2308 with the correct dependency commit

## What is the purpose of the change

Point the cosmos sdk dependency to the correct commit 

## Brief Changelog
Point the cosmos sdk dependency to the correct commit 

## Testing and Verifying

This change is a trivial rework / code cleanup without any test coverage.

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (/ no)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (/ no)
  - How is the feature or change documented? (not applicable )

### CODE REVIEW

**Comment by nicolaslara** [comment]
hmm, apparently this sdk fork commit is also causing issues (mostly on simtypes and e2e): https://github.com/osmosis-labs/cosmos-sdk/commit/059c959ca0b9a341483ce2cbef0cf3884f8f6a19. CC @czarcas7ic

**Comment by czarcas7ic** [comment]
@nicolaslara I utilized the commit prior to that (934d0d94bef8b62e656c6a142223ecd12fa9a4c9) and it passes CI (https://github.com/osmosis-labs/osmosis/pull/2419)

I would say it has to be the most recent PR to the SDK fork then

**Comment by nicolaslara** [comment]
ahh but this makes sense then. It's basically that #2419 needs to be merged before this PR.

**Comment by czarcas7ic** [comment]
@nicolaslara Just a heads up, the PR you were waiting for has been merged!

**Comment by nicolaslara** [comment]
great! I'll update this so it can be merged

**Review by ValarDragon — APPROVED** [review]

**Pull request merged**
