### PR TITLE
Create Gamm helper method to manipulate into given spot price

### PR DESCRIPTION
**Pull request by ThanhNhann**
Closes: #3003 

## What is the purpose of the change

Create Gamm helper method to manipulate into given spot price

## Brief Changelog

- Add a new way we can get the target spot price in a pool

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? no
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? no
  - How is the feature or change documented?  not documented

### CODE REVIEW

**Comment by ThanhNhann** [comment]
Hi @mattverse, can you check this implementation

**Review by czarcas7ic — APPROVED** [review]
All the logic here LGTM! The only thing I am concerned about is some of the logic might need to get flipped after this is merged (should be merged by end of day)

https://github.com/osmosis-labs/osmosis/pull/3191

**Comment by ThanhNhann** [comment]
I have update logic, can you plz check it @czarcas7ic

**Comment by czarcas7ic** [comment]
LGTM, want another review before merge

**Review by ValarDragon — APPROVED** [review]
LGTM, ty for the PR! (Sorry late review)

In future perhaps we switch to a binary search impl here

**Pull request merged**
