### PR TITLE
Always use latest golangci-lint

### PR DESCRIPTION
**Pull request by faddat**
## Description

This will always use the latest golangci-lint, so we don't need to update that. 

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by ValarDragon** [comment]
Is this a good idea? Wouldn't it be worse if golangci had a breaking change, and then our ci broke, breaking workflows for a few days?

**Comment by faddat** [comment]
heh, all I can say on this topic is that in my experience, it doesn't :).

**Comment by faddat** [comment]
but that doesn't mean that it won't!

:upside_down_face:

**Comment by faddat** [comment]
https://github.com/cosmos/gaia/runs/4489341951?check_suite_focus=true

**Comment by ValarDragon** [comment]
I'd really prefer to have CI versions pinned for determinism, especially long term. Do we anticipate a lot changing between golangci versions?

**Comment by faddat** [comment]
I anticipate linter deprecation, resulting in errors

**Comment by faddat** [comment]
Screen Shot 2021-12-12 at 6 46 55 PM


They're warnings :).  Let's keep as is.

**Pull request closed without merging**
