### PR TITLE
lint: tighten linting

### PR DESCRIPTION
**Pull request by faddat**
Closes: #1939 

## What is the purpose of the change

* This PR will tighten linting across osmosis v12. 
* style
  * I changed instances of Asset and Basset to assetA and assetB since they didn't need to be exported, and the latter reads more easily. 

## Brief Changelog

* enable revive linter, with below exclusions:

```yaml
  exclude:
    - "var-naming"
```

## Testing and Verifying

This PR should not change any APIs or the function of any code.  If it does, it should be rejected. 

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? no
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? not yet
  - How is the feature or change documented? in changelog

### CODE REVIEW

**Comment by faddat** [comment]
@ValarDragon @p0mvn -- hey :D.

So, I removed the exclusion of stableswap from the unused linter, but there and still many things unused.  

I'm thinking that I should tag them like:

```go
//nolint:unused
```

**Comment by ValarDragon** [comment]
I found the golangci lint comments quite helpful!

I also don't agree with most of the changes as net beneficial. (Though I also don't think deliberation around them is particularly helpful either)

**Comment by faddat** [comment]
I agree about not deliberating, so if this doesn't seem real useful, I can just close this, OR I can revert some of the changes and comment them.

**Comment by ValarDragon** [comment]
Want to PR just revive + your exclusions?

**Pull request closed without merging**
