### PR TITLE
Prefixes change, use of unix time to save db space

### PR DESCRIPTION
**Pull request by RusAkh**
Closes: #2251 

## What is the purpose of the change

Saving database space by using unix time rather than UTC + by using shorter prefixes

## Brief Changelog

Before: "historical_pool_index|1|2009-11-10T23:00:00.000000001|"
After: "HPInd|1|UNIX_TIME_HERE|"

Prefixes change:
historical_pool_index -> HPInd
historical_time_index -> HTInd
recent_twap -> RTwap
## Testing and Verifying

This change is a trivial rework / code cleanup without any test coverage.

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? no
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? no
  - How is the feature or change documented? not documented

### CODE REVIEW

**Review by mattverse — COMMENTED** [review]
Thanks for tackling this issue! 

I generally agree on using formatInt to reduce format time, but I feel a little conflicted on changing the seperator keys into short hand(considering that it get's complicated to debug with the prefixes + I don't think much storage would be reduced by changing seprators into shorthand). Also want to hear what other reviewers think about this

**Comment by p0mvn** [comment]
Thanks for this work! Although I originally created this issue, I agree with Matt now.

Now, that v12 is finalized and code freezed, changing database keys would require migration for the subsequent releases. Given that this is not a current bottleneck, I think the migration overhead is not justified.

So I think we should keep the summary of the discoveries and this PR in mind if we ever need to optimize the database layout in the future

**Comment by faddat** [comment]
cool!  So, there were a number of ideas we explored behind this-- for example, making a .proto file, since I believe that protobuf would compress these items natively.

We also tried the s2 compression library, and found it actually increased the size of data stored.

**Comment by ValarDragon** [comment]
Agreed with @p0mvn, unfortunately I think we do need to close unfortunately.

The TWAP code is code frozen aside from bug fixes, and this would require a state migration post-inclusion that seems not worth the marginal saving

Re: compression, that fundamentally doesn't make sense here unfortunately, since we need to preserve sort and length ordering guarantees.

Re: prefix truncation: This is definitely not worth it imo, and is an optimization that should exist at the DB level for keys (which I believe most do, via tries )

**Pull request closed without merging**
