### PR TITLE
Chore/CI for typo

### PR DESCRIPTION
**Pull request by hoangdv2429**
Closes: #XXX

## What is the purpose of the change

This PR will add CI for check typo per PR and push on main.

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes?
  - [x] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented? 
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [ ] N/A

### CODE REVIEW

**Comment by hoangdv2429** [comment]
@mattverse It's not the best way to do it but I guess this will work. If anything need changes please ping me, thank you!

**Comment by czarcas7ic** [comment]
Can you display this working by spelling something wrong in a random markdown and linking that it catches that error?

Maybe use "somthing" instead of "something"

**Comment by hoangdv2429** [comment]
@czarcas7ic Thank you! I closed the last PR. Will try to trigger the check rn.

**Comment by hoangdv2429** [comment]
@czarcas7ic you have to actually make a typo. Funton is counted as variable name apparently.. It triggered properly now.

**Comment by hoangdv2429** [comment]
Merge main and there is already some typos...

**Review by pysel — APPROVED** [review]
utACK! nice! thanks!

**Review by p0mvn — APPROVED** [review]

**Pull request merged**
