### PR TITLE
Add missing interface to `osmosis.incentives.CreateGroupsProposal` protobuf

### PR DESCRIPTION
**Pull request by NoahSaso**
## What is the purpose of the change

The `osmosis.incentives.CreateGroupsProposal` protobuf type is missing an interface implementation statement.

## Testing and Verifying

This change is a trivial rework / code cleanup without any test coverage.

## Documentation and Release Note

  - [x] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented? 
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [x] N/A

### CODE REVIEW

**Review by mattverse — APPROVED** [review]
Awesome! Thanks :)

**Comment by czarcas7ic** [comment]
@NoahSaso can you run `make proto-all` and then push those changes

**Comment by NoahSaso** [comment]
> @NoahSaso can you run `make proto-all` and then push those changes

gotchu 🤝

**Comment by mattverse** [comment]
> @NoahSaso can you run `make proto-all` and then push those changes

@czarcas7ic  I've noticed our check-proto CI failing when an external contributor has created a PR 🤔 We should definitely come back and fix it but should be good to merge for now :)

**Pull request merged**
