### PR TITLE
test: start epoch 45 minutes after upgrade for testnets

### PR DESCRIPTION
**Pull request by czarcas7ic**
Closes: #XXX

## What is the purpose of the change

As discussed in chain dev call, we want to test VS incentives on testnets, but we don't want to modify the actual epoch duration. This change checks if the chain ID is not osmosis-1. If it is not, it sets the epoch to start 45 minutes after upgrade. This should give enough time to create volume and then check if the incentives are split as expected.

This PR also exports the SetEpochInfo method in the epochs module. This is fine imo.

## Testing and Verifying

Pretty trivial change, can add tests if we think it's needed.

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes?
  - [ ] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented? 
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [ ] N/A

### CODE REVIEW

**Comment by mattverse** [comment]
just curious, what's the reason we have so much go.mod and go.sum diffs across all sub modules?

**Review by mattverse — COMMENTED** [review]
IMO feels wierd to have this merged to main, maybe because I am lacking context in teh specific reason we need this. Do we have any reason we're doing this instead of manually changing genesis state as we did with altering other testnet states?

**Comment by pysel** [comment]
> just curious, what's the reason we have so much go.mod and go.sum diffs across all sub modules?

one of submodules were changed (`epochs`), so go.mods had to be updated, _czarcas7ic_ ran auto go.mod update workflow, which tidied all submodules, hence the changes

**Comment by czarcas7ic** [comment]
@mattverse so the reason I think this should be merged is:

When we upgrade public testnet, it would be nice to just get through the first epoch ASAP so we can start testing the subsequent epochs. We decided against separate branches for this logic since it gets confusing for people to need separate tags for testnet

**Comment by czarcas7ic** [comment]
Closing as we have already upgrade the testnet

**Pull request closed without merging**
