### PR TITLE
Semver for the v3.x series of Osmosis

### PR DESCRIPTION
**Pull request by faddat**
This adds a /v3 import path to osmo and its modules so that devs can use it more easily.

### CODE REVIEW

**Comment by ValarDragon** [comment]
Thanks for adding this 🙏

**Comment by ValarDragon** [comment]
Looks like mint modules cli_test needs to be updated. Once tests pass, this is good to merge imo

**Comment by faddat** [comment]
was a little more than that.  We hit a conflict on sdk.error

**Review by ValarDragon — APPROVED** [review]
Amazing, tysm for adding this in!

**Pull request merged**
