### PR TITLE
chore[e2e]: faster epoch

### PR DESCRIPTION
**Pull request by czarcas7ic**
Closes: #XXX

## What is the purpose of the change

Epoch is currently set to 1 minute. There are two tests that wait for an epoch to pass before continuing in the e2e test suite. This means we could potentially have to wait up to a minute to continue the test. There is no need for this, so we should just speed up the epoch duration more.

## Testing and Verifying

Built locally, and tested against the currently open e2e PR against main

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes?
  - [ ] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented? 
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [ ] N/A

### CODE REVIEW

**Comment by czarcas7ic** [comment]
@devbot-wizard add changelog misc

**Comment by czarcas7ic** [comment]
@devbot-wizard add changelog misc

**Comment by ValarDragon** [comment]
@devbot-wizard add changelog misc

**Comment by czarcas7ic** [comment]
@devbot-wizard add changelog misc

**Comment by czarcas7ic** [comment]
@devbot-wizard add changelog misc

**Comment by czarcas7ic** [comment]
@devbot-wizard add changelog misc

**Comment by ValarDragon** [comment]
@devbot-wizard add changelog misc

**Review by ValarDragon — APPROVED** [review]

**Pull request merged**
