### PR TITLE
remove bech32 ibc

### PR DESCRIPTION
**Pull request by sunnya97**
Closes: #XXX

## What is the purpose of the change

This PR removes bech32 ibc from the state machine, because it is unmaintained.

## Brief Changelog

*(for example:)*
 
  - *The metadata is stored in the blob store on job creation time as a persistent artifact*
  - *Deployments RPC transmits only the blob storage reference*
  - *Daemons retrieve the RPC data from the blob cache*

## Testing and Verifying

*(Please pick one of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added unit test that validates ...*
  - *Added integration tests for end-to-end deployment with ...*
  - *Extended integration test for ...*
  - *Manually verified the change by ...*

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (yes / no)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (yes / no)
  - How is the feature or change documented? (not applicable   /   specification (`x/<module>/spec/`)  /  [Osmosis docs repo](https://github.com/osmosis-labs/docs)   /   not documented)

### CODE REVIEW

**Comment by sunnya97** [comment]
I can't fully remove bech32 ibc repo as a dependency because its used in the v5 upgrade code.  Is it okay to remove old upgrade migrations from newer code releases?

**Comment by ValarDragon** [comment]
yeah, just comment out those lines

**Review by ValarDragon — APPROVED** [review]
LGTM. 

E2E test atm covers sends working AFAIK, so should be confident things are still working. CC'ing @p0mvn to confirm

**Review by p0mvn — APPROVED** [review]
LGTM - yes as long as e2e tests pass, this should be safe IMO

**Pull request merged**
