### PR TITLE
fix: patch export genesis cosmwasm pool type

### PR DESCRIPTION
**Pull request by czarcas7ic**
Closes: #XXX

## What is the purpose of the change

CW pools do not have an "afterPoolCreated" hook to create an internal gauge. Therefore, if a pool is created and we attempt to state export, we error on exporting gauges for the CW pool.

This is a temp patch. We will need to eventually create gauges for CW pools via a hook.

## Testing and Verifying

Currently testing with osmosis-ci.

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes?
  - [ ] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented? 
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [ ] N/A

### CODE REVIEW

**Comment by czarcas7ic** [comment]
devbot help

**Comment by devbot-wizard** [comment]
Hi! I'm DevBot, a bot that helps with common tasks in the development process. Commands:
- `devbot fix`: Fix basic errors in the PR. (e.g. imports, changelog conflicts, go mod conflicts)
- `devbot merge base`: Merge the base branch into the PR branch.
- `devbot add changelog [misc/feat/bug/api/sec] [message]`: Add a changelog entry to the PR. (e.g. `devbot add changelog feat Added a new feature`)
    - If message is blank, defaults to PR title.
- `devbot re-pr`: Re-PR the PR, useful for external contributors where we have no edit perms.

**Comment by czarcas7ic** [comment]
devbot add changelog bug

**Comment by czarcas7ic** [comment]
Closing as this was hacky patched by @PaddyMc, need to get the real fix in next

**Pull request closed without merging**
