### PR TITLE
Database stability improvements

### PR DESCRIPTION
**Pull request by p0mvn**
Closes: #XXX

## Description

- upgraded iavl and SDK with the most recent database stability improvements
- changelog updated

______

For contributor use:

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [x] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [x] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Review by ValarDragon — APPROVED** [review]
LGTM! Is the changing the hardcoded constant from 780k to 100k in this branch as well? (I didn't see it on skim in IAVL / cosmos SDK changes)

I think we should publish a release once thats in

**Comment by p0mvn** [comment]
@ValarDragon I'm working on that today to represent the limit in terms of bytes and as a configurable value. Hoping to be done by EOD and merge in a separate PR.

If you'd like to get it out ASAP, I can hardcode to 100K instead of the configurable bytes alternative

**Comment by ValarDragon** [comment]
Oh sweet, didn't realize your going for the limit in bytes at the moment, I thought that was something we'd do much later in the future. I think we should change it to 100k and get that into a release (the release can still come out tomorrow!)

I'm in favor of the limiting by bytes and a config value, but I don't think we should block the next release on that

**Comment by p0mvn** [comment]
Sounds good. I will prepare the PRs with 100K right now.

Will still keep working on the configurable value. If that doesn't get in before the next release, that's okay.

**Comment by ValarDragon** [comment]
My main thinking as to why, is because we may get unforeseen troubles that would delay a release to mid-week with the change to bytes. (E.g. some unexpected edge case, takes longer to review on time, etc.)

I would rather get this out sooner, so we can get more information around the app hash situation, and mitigate the ongoing RAM usage concerns

**Comment by ValarDragon** [comment]
Yeah, we can still make a release as soon as the config gets done / merged!

**Comment by p0mvn** [comment]
@ValarDragon updated sdk and iavl with smaller fast node cache size. Also, prepared changelog for `v7.1.0` release

**Pull request merged**
