### PR TITLE
Attempt to add regex replacement of denom validation

### PR DESCRIPTION
**Pull request by mattverse**
Closes: #XXX

## What is the purpose of the change
Updates SDK commit to include regex replacement of denom validation

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes?
  - [ ] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented?
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [ ] N/A

### CODE REVIEW

**Review by ValarDragon — APPROVED** [review]

**Comment by ValarDragon** [comment]
this isn't state compatible?

**Comment by czarcas7ic** [comment]
Lets get this back into sdk main, tag sdk main, and then update tag here

**Comment by mattverse** [comment]
@czarcas7ic Sounds good, just wanted to open this test PR to ensure this doesnt break anything our side. Will re-revert PR there and create a new PR for this

**Comment by czarcas7ic** [comment]
@mattverse I am doing so now, thanks for testing!

**Pull request closed without merging**
