### PR TITLE
chore: reuse docker containers when generating protobuf files

### PR DESCRIPTION
**Pull request by robert-zaremba**
* fixing the image version to the latest released (`@latest` is not good)
* optimizing the `make proto-gen` job by reusing proto containers instead of removing them all the time.

### CODE REVIEW

**Review by ValarDragon — APPROVED** [review]
Oh amazing, this may have been the problem with my local docker install as well

**Comment by ValarDragon** [comment]
Oh hrmm, doesn't work on my local docker install. I get
```
make proto-gen
Generating Protobuf files
/third_party/proto: does not exist
make: *** [proto-gen] Error 1
```

I'll check on my separate build server though, since make proto-gen didn't work on my laptop before either

**Comment by robert-zaremba** [comment]
```
/third_party/proto: does not exist
```
sounds like a dependency problem with the cosmos-sdk. It's strange, because in SDK we are using the same docker container (v0.2) for 0.42 builds.
could you remove your docker images and containers and recheck?

**Comment by ValarDragon** [comment]
@mattverse pointed out that the problem was that I have a local vendor directory. Not sure why that causes issues, but it does 😕 .

After deleting my vendor folder, both this branch and main worked for me!

**Review by ValarDragon — APPROVED** [review]
Thanks for fixing this!

**Comment by robert-zaremba** [comment]
Cool, happy that it works and thanks for merging.

> the problem was that I have a local vendor directory

Ah, most likely you had proto files in that directory. The proto compilation scrip is importing all proto files and tries to compile them: https://github.com/osmosis-labs/osmosis/blob/main/scripts/protocgen.sh#L12

**Comment by ValarDragon** [comment]
Ahh thanks, looks like we just need to add the line for ignoring the vendor directory there. I'll submit a PR here and on the SDK for that!

**Pull request merged**
