### PR TITLE
Rocksdb state sync script

### PR DESCRIPTION
**Pull request by faddat**
Closes: #695 

## Description

This adds statesync-rocks.bash to the `scripts` folder.  It is a rocksdb compatible state sync script for osmosis. 

______

For contributor use:

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [x] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by faddat** [comment]
I think that I now have enough information to use this as where I make the rocksdb guide.

**Comment by faddat** [comment]
To get this in, I'm going to mark this as `ready for review` and bundle docs with #876

**Comment by ValarDragon** [comment]
Sorry didn't notice this getting marked ready for review, my bad

**Comment by faddat** [comment]
@ValarDragon no problem. 

I think I should close this for now, and focus on work upstream to make state sync work with wasm

**Comment by ValarDragon** [comment]
Thanks for the info!

**Pull request closed without merging**
