### PR TITLE
chore: Have our own proto build env image

### PR DESCRIPTION
**Pull request by faddat**
This will allow us to have a proto build env image of our own, automatically built when it needs to be. 

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (yes / no)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (yes / no)
  - How is the feature or change documented? (not applicable   /   specification (`x/<module>/spec/`)  /  [Osmosis docs repo](https://github.com/osmosis-labs/docs)   /   not documented)

### CODE REVIEW

**Comment by ValarDragon** [comment]
can you explain in a github issue, more of the overarching reason of why we should do this? I don't really understand why we shouldn't use the process we do rn with the SDK image? (I don't have a great reason for it either - but this is a degree of context thats needed before this can be reviewed)

**Comment by faddat** [comment]
I prefer to use the SDK image... just need to get it working.  

How about, if I don't get auto builds there working, then I make the issue.

If I do, I close this

**Comment by mattverse** [comment]
just curious, does the current SDK image have problems or bugs?

**Comment by faddat** [comment]
Not exactly.  I just haven't gotten it to work with ghcr.io just yet. 

Also, I'm pretty sure that they all have bugs, including the sdk one.  I have yet to see protobuf things work fully smoothly on any repo.

**Comment by faddat** [comment]
I am going to close this, because the sdk reacted really oddly to go v1.19

**Pull request closed without merging**
