### PR TITLE
Proto: camelCase to snake_case

### PR DESCRIPTION
**Pull request by hieuvubk**
Closes: #701

### CODE REVIEW

**Review by alexanderbez — APPROVED** [review]
utACK (did a quick skim)

**Review by ValarDragon — APPROVED** [review]
Lgtm, ty!!

**Comment by ValarDragon** [comment]
Can you add a breaking change entry in the changelog? (Also in the future can you fill out the PR template please!)

Btw, also added you to the 'notional' github team, so in the future you can branch off the repo directly

**Comment by pyramation** [comment]
utACK as well! @Thunnini can you take a look to verify this will change amino encoding on FE? I have a pretty good idea of the implications but have not tested.

This change would like require we update FE amino converter implementations (to be more like how it's done with cosmos package with underscore<->camel instead of camel<->camel). So in a sense, this is a good move in the right direction, and how other packages seem to be doing it.

**Comment by hieuvubk** [comment]
> Can you add a breaking change entry in the changelog? (Also in the future can you fill out the PR template please!)
> 
> Btw, also added you to the 'notional' github team, so in the future you can branch off the repo directly

thank u, i edited changelog

**Comment by pyramation** [comment]
thanks for updating all of these! super helpful. Let's coordinate a migration plan with @Thunnini @jonator for v9 or v10 so we can test this with FE.

**Comment by hieuvubk** [comment]
@ValarDragon Va @pyramation 
I just gone through proto files and encountered some special cases in the _txfees_ module
Ảnh chụp Màn hình 2022-06-05 lúc 13 04 04
Ảnh chụp Màn hình 2022-06-05 lúc 13 04 25
Neither camelCase nor snake_case, so any change will affect to other code. What do u think?

**Comment by pyramation** [comment]
> @ValarDragon Va @pyramation I just gone through proto files and encountered some special cases in the _txfees_ module Ảnh chụp Màn hình 2022-06-05 lúc 13 04 04 Ảnh chụp Màn hình 2022-06-05 lúc 13 04 25 Neither camelCase nor snake_case, so any change will affect to other code. What do u think?

I don't believe we're using those fields in FE yet — would it make sense to rename those to `fee_token` and `pool_id`?

**Comment by hieuvubk** [comment]
> > @ValarDragon Va @pyramation I just gone through proto files and encountered some special cases in the _txfees_ module Ảnh chụp Màn hình 2022-06-05 lúc 13 04 04 Ảnh chụp Màn hình 2022-06-05 lúc 13 04 25 Neither camelCase nor snake_case, so any change will affect to other code. What do u think?
> 
> I don't believe we're using those fields in FE yet — would it make sense to rename those to `fee_token` and `pool_id`?

Oh i mean in chain code

**Comment by ValarDragon** [comment]
Hey, this probably shouldn't have been merged yet, adjusting perms to improve this in the future.

Going to make a follow-up issue, to ensure we have a plan for how significant is this breaking change, and if we should revert it or bundle it with another large breaking change in the future.

**Comment by ValarDragon** [comment]
Eh, its not that huge of a deal.

Going to make the issue for us to decide in

**Pull request merged**
