### PR TITLE
fix: script to start a local node

### PR DESCRIPTION
**Pull request by fkneeland-figure**
Closes: #XXX

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by ValarDragon** [comment]
is prepare-mainnet still needed? I thought we fixed the issue, cc @UnityChaos

**Comment by mattverse** [comment]
Should not be needed, as of my knowledge, it was included in v6.0 upgrade

**Comment by mattverse** [comment]
Commited in 6.x branch per https://github.com/osmosis-labs/osmosis/pull/655, should not be needed

**Comment by fkneeland-figure** [comment]
👍 I ran some tests on main and it works, although not on v6.0.0

**Comment by ValarDragon** [comment]
Ah true, I'll tag a v6.0.1 branch with this

**Pull request closed without merging**
