### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by faddat**
I figure these belong approximately in that spot.  We can try state sync when 2.0 comes!

### CODE REVIEW

**Comment by faddat** [comment]
Adding genesis now, kinda neglected that.

**Comment by faddat** [comment]
I could also adapt this to use cosmos-omnibus?

**Review by ValarDragon — COMMENTED** [review]
Instructions look great to me!

I think we should put this into `networks`, and have this repo point to the instructions there. What are other folks thoughts on this?

**Comment by thecryptodrive** [comment]
@ValarDragon I think that is a great idea, I'm actually putting together a longer form instruction set with more verbosity and additional dependencies installs, will share soon.

**Comment by antstalepresh** [comment]
> @ValarDragon I think that is a great idea, I'm actually putting together a longer form instruction set with more verbosity and additional dependencies installs, will share soon.

**Comment by faddat** [comment]
@ValarDragon I assure you that the pattern of putting this info in `networks` super confuses newcomers.

Hence I propose that this repo's readme be like:

Product definition

(Osmosis is........)


Quick start


Other stuff

**Review by faddat — COMMENTED** [review]
changed to v1.0.2 ; had some issues with .3 the other day.

**Comment by xla** [comment]
This PR if merged would have saved me a good 20mins on running a full node locally.

**Comment by faddat** [comment]
@xla I'll update e'r and we'll get e'r merged.

**Review by ValarDragon — APPROVED** [review]

**Pull request merged**
