### PR TITLE
perf: improve CL KVStore entries

### PR DESCRIPTION
**Pull request by czarcas7ic**
Closes: #4733 

## What is the purpose of the change

The current `Owner | Pool ID | Position ID -> Position ID` KVStore returns values like so:

```
addr1|1|1->1
addr1|1|2->2
addr1|2|3->3
addr2|1|4->4
addr2|1|5->5
```

This PR instead keys `Owner | Pool ID -> list of Position IDs` like so:

```
addr1|1|->[1, 2]
addr1|2|->[3]
addr2|1|->[4,5]
```

Similarly, this PR keys `Pool ID -> list of Position IDs` like so:

```
pool1->[1,3,5,6]
pool2->[2,4,7]
```

## Testing and Verifying

- DeletePosition and CreatePosition tests modified to expect positionIds returned from the KVStore
- Osmoutils additions (SliceContains, RemoveFromSlice, BigEndianToUint64Slice, and Uint64SliceToBigEndian) have corresponding tests

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes?
  - [ ] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented? 
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [ ] N/A

### CODE REVIEW

**Comment by p0mvn** [comment]
oh perfect! I was going to start working on this today for further perf improvements

**Comment by czarcas7ic** [comment]
Yeah, was not super hard to do and feels like it will save a ton of space :)

**Comment by czarcas7ic** [comment]
@p0mvn I think its less of a performance change and more of a storage change. The current keys feel silly / redundant. We also have informal starting their audit tomorrow, so this would be a part of the scope. IMO I think if we don't get this in now we will never get it in, and we will have a bunch of silly redundant state that is not needed.

**Comment by mattverse** [comment]
> @p0mvn I think its less of a performance change and more of a storage change. The current keys feel silly / redundant. We also have informal starting their audit tomorrow, so this would be a part of the scope. IMO I think if we don't get this in now we will never get it in, and we will have a bunch of silly redundant state that is not needed.

Sorry, I think I might be lacking context. What or how does this improve existing way of storing state? At a brief glance, this PR seems more like style change more than storage efficiency change, I think I might be missing some details tho

**Comment by czarcas7ic** [comment]
As discussed in call, closing this in favor of https://github.com/osmosis-labs/osmosis/pull/5237

Thanks for all the reviews, was still helpful in getting to our final result :)

**Pull request closed without merging**
