### PR TITLE
Add min token out for Balancer Pool <> CL Pool Migrations

### PR DESCRIPTION
**Pull request by mattverse**
Closes: https://github.com/osmosis-labs/osmosis/issues/4539

## What is the purpose of the change

The current migration logic between Balancer Pool and CL Pool had issues with trying to migrate small gamm shares, since the migration logic was consisted of 1) exit pool 2) use the coins resulted from (1) to create position, while exit pool using dust shares would leave the user to leave pool without any coins. In this case the method would attempt to join pool with 0 coins, resulting the method to error. 

This PR tries to solve this problem by adding min token out field in the msg field for the migration message and the method itself. 

With the min token out, each position in existing Balancer Pool are given freedom to exit pool with the amount they are intending to have. 

## Brief Changelog

- Add min token out for Balancer Pool <> CL Pool Migrations

## Testing and Verifying

Add test cases. 

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (yes / no)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (yes / no)
  - How is the feature or change documented? (not applicable   /   specification (`x/<module>/spec/`)  /  [Osmosis docs repo](https://github.com/osmosis-labs/docs)   /   not documented)

### CODE REVIEW

**Comment by p0mvn** [comment]
Converted to draft since CI is failing

**Comment by mattverse** [comment]
Fixed tests :)

**Review by p0mvn — APPROVED** [review]

**Comment by czarcas7ic** [comment]
What about the migration of locked shares in superfluid? I imagine the potential to have this issue is also capable there as well right?

**Comment by mattverse** [comment]
As discussed in call, planning to address the other side of migration logic once https://github.com/osmosis-labs/osmosis/pull/4885 has been merged. 

Created an issue https://github.com/osmosis-labs/osmosis/issues/4959 to track this

**Review by czarcas7ic — APPROVED** [review]

**Pull request merged**
