### PR TITLE
chore: bump sdk and cometbft

### PR DESCRIPTION
**Pull request by PaddyMc**
## What is the purpose of the change

Bumping cometbft and cosmos sdk to the lastest versions:

comet => https://github.com/osmosis-labs/cometbft/releases/tag/v0.38.12-v26-osmo-2
cosmossdk => https://github.com/osmosis-labs/cosmos-sdk/releases/tag/v0.50.10-v26-osmo-2

### CODE REVIEW

**Comment by czarcas7ic** [comment]
Shouldn't we be updating https://github.com/osmosis-labs/cometbft/tree/osmo/v0.38.x instead of creating an entirely new branch?

**Comment by czarcas7ic** [comment]
https://github.com/osmosis-labs/cometbft/blob/osmo/v0.38.12/CHANGELOG.md#osmosis-specific-changes

I am a bit confused on this, everything below 1c07c7c is newly added, there is no way all of these changes are Osmosis specific changes that are not upstreamed right?

**Comment by czarcas7ic** [comment]
It seems we are using an osmo/v0.38.12 branch for our comet fork, but are still using the osmo/v0.50.x branch for the sdk. Can we keep the same standard between these repos?

**Comment by czarcas7ic** [comment]
Reading the changelog in the sdk fork that you tagged:

https://github.com/osmosis-labs/cosmos-sdk/blob/v0.50.10-v26-osmo-1/CHANGELOG.md#v050x-v26-osmo-1

This commit is from 5 months ago, so I assume this was not updated to match where we forked off the sdk.

**Comment by PaddyMc** [comment]
> Shouldn't we be updating https://github.com/osmosis-labs/cometbft/tree/osmo/v0.38.x instead of creating an entirely new branch?

This wasn't as easy as expected, I think creating a new branch is actually the best way to do this.

e.g => https://github.com/osmosis-labs/cometbft/blob/osmo/v0.38.12/CHANGELOG.md

This is a branch for cometbft now I think you're right tho, i'll create a branch for both v26 and v27 with the prefix for each, to make it easier to know which is which.

&& 

https://github.com/osmosis-labs/cosmos-sdk/tree/osmo-v27/0.50.10 => this is the commit for the cosmos-sdk

**Comment by PaddyMc** [comment]
> Reading the changelog in the sdk fork that you tagged:
>
> https://github.com/osmosis-labs/cosmos-sdk/blob/v0.50.10-v26-osmo-1/CHANGELOG.md#v050x-v26-osmo-1
>
> This commit is from 5 months ago, so I assume this was not updated to match where we forked off the sdk.

Ah sorry I forgot to update the changelog there will do that now :sweat:

**Comment by PaddyMc** [comment]
So updated the branches and changelogs of each! Lmk what you think, I think this is the pattern we should follow going forward

e.g
https://github.com/osmosis-labs/cosmos-sdk/tree/osmo-v26/0.50.10

&&

https://github.com/osmosis-labs/cometbft/tree/osmo-v26/0.38.12

**Review by czarcas7ic — APPROVED** [review]

**Pull request merged**
