### PR TITLE
Backport v4.2.0 updates to main

### PR DESCRIPTION
**Pull request by ValarDragon**
Closes: #591 

## Description

Backports the v4.2.0 fixes to main. I simplified the NewMempoolMaxGasPerTxDecorator decorator substantially, since the fees have been relegated to our own separate ante-handler.

The rest of the changes are essentially direct cherry-picks.

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by ValarDragon** [comment]
Note: This PR should be rebased and merged, not squashed.

**Review by mattverse — COMMENTED** [review]
One question I have is about NewMempoolMaxGasPerTxDecorator, wouldn't it be better to user params / gov to decide maximum gas wanted instead of hardcoding it? 
Do we have future plans on changing this or would this be a fixed way that we would manage max gas in the future as well?

**Comment by ValarDragon** [comment]
This is in CheckTx, not consensus. (So it only impacts whether a tx gets into the mempool) So every node can just change this locally.

I think we should expose this via a config, but we can do that in a state-compatible update later. (As that decorator doesn't affect consensus logic at all!)

**Review by mattverse — APPROVED** [review]
Cool! Otherwise looks LGTM!

**Pull request merged**
