### PR TITLE
whitelist lockup query AccountLockedCoins

### PR DESCRIPTION
**Pull request by Buckram123**
## What is the purpose of the change

This PR adds lockup query(namely AccountLockedCoins) to stargate query whitelist.

## Documentation and Release Note

  - [x] Does this pull request introduce a new feature or user-facing behavior changes?
  - [x] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?
  
  ## Background
 - lockup.query/AccountLockedCoins: We build an cosmwasm app, for multiple staking providers, on different chains, that has the same API. Except our "query_staked(staking_token, staker_address)" method currently is not implementable on osmosis, because contracts can't query `AccountLockedCoins`.

### CODE REVIEW

**Comment by sunnya97** [comment]
QueryProposal can have pretty unknown gas costs, especially if its a CosmWasm prop, that needs to load the entire code

**Comment by Buckram123** [comment]
> QueryProposal can have pretty unknown gas costs, especially if its a CosmWasm prop, that needs to load the entire code

Sure, whitelisting `QueryAccountLockedCoins` more important to us. There are no issues with that query?

**Review by ValarDragon — COMMENTED** [review]
So we can add this, but warning that this can have unbounded gas and you probably don't want to actually use this in production. You'd much rather have the FE get the lock-id's, and then do the query based on provided lock ID's

I'm happy to add this in, just warning that may not work how you want

The issue is that it iterates over every single lock the user has. So if they've LP'd in like 50 different pools, thats quite expensive gas wise! (And you probably only care about a small subset)

**Comment by ValarDragon** [comment]
(Just trying something, will delete this)
@devbot re-pr

**Comment by ValarDragon** [comment]
(Just trying something, please ignore)
@devbot re-pr

**Comment by ValarDragon** [comment]
(Just testing something please ignore)
@devbot re-pr

**Comment by ValarDragon** [comment]
devbot re-pr

**Comment by ValarDragon** [comment]
devbot re-pr

**Comment by ValarDragon** [comment]
(Ignore this message just testing something)
devbot re-pr

**Comment by ValarDragon** [comment]
(Ignore this message just testing something)
devbot re-pr

**Comment by p0mvn** [comment]
Hi @Buckram123 . Based on the latest reply, would you still like to get this whitelisted?

**Comment by Buckram123** [comment]
> Hi @Buckram123 . Based on the latest reply, would you still like to get this whitelisted?

Hey, yes, that would be really helpful!

**Comment by p0mvn** [comment]
Could you please resolve the conflict?

Also, do you mind summarizing [ValarDragon's reply](https://github.com/osmosis-labs/osmosis/pull/5906#pullrequestreview-1565797320) via comment above the line whitelisting this query?

**Comment by Buckram123** [comment]
@p0mvn done!

**Review by p0mvn — APPROVED** [review]
Thanks!

**Comment by p0mvn** [comment]
Merging since all requests have been addressed

**Pull request merged**
