### PR TITLE
feat(x/twap): geometric twap code gen query boilerplate

### PR DESCRIPTION
**Pull request by p0mvn**
Closes: #XXX

## What is the purpose of the change

Geometric twap code generated query boilerplate.

Marked as state compatible because query has not been whitelisted yet.

## Brief Changelog

- update proto files
- `make proto-all`
- `make run-query-gen`

### CODE REVIEW

**Comment by ValarDragon** [comment]
Query wrap LGTM, presumably in draft due to waiting for constituent PRs to get in?

**Comment by p0mvn** [comment]
> Query wrap LGTM, presumably in draft due to waiting for constituent PRs to get in?

Yes, merging: https://github.com/osmosis-labs/osmosis/pull/3809 and then marking this as ready

**Comment by p0mvn** [comment]
@ValarDragon this is R4R for a quick ACK

**Review by ValarDragon — APPROVED** [review]
LGTM

**Pull request merged**
