### PR TITLE
fix: Incorrect `cosmos_sdk_version` in the `/cosmos/base/tendermint/v1beta1/node_info` query 

### PR DESCRIPTION
**Pull request by Ryz0nd**
Closes: #5925

## What is the purpose of the change

> Add a description of the overall background and high level changes that this PR introduces

*(E.g.: This pull request improves documentation of area A by adding ....*

## Testing and Verifying

*(Please pick one of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added unit test that validates ...*
  - *Added integration tests for end-to-end deployment with ...*
  - *Extended integration test for ...*
  - *Manually verified the change by ...*

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes?
  - [ ] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented? 
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [ ] N/A

### CODE REVIEW

**Comment by ValarDragon** [comment]
Hey, unfortunately don't think were going to be able to merge this if the key fix is based on changing whats in the go.mod. 

That unfortunately changes everytime we do go mod tidy.

**Comment by Ryz0nd** [comment]
@ValarDragon I'm not sure if there's a stable place where the SDK version is listed.

As for updating the SDK version solely through the `make update-sdk-version` command, I'm curious if there are any limitations to that approach.

**Comment by ValarDragon** [comment]
Yeah, the issue is every time we do `go mod tidy` or theres any dependency update, the standard go tooling forces a bump of this SDK version

**Comment by ValarDragon** [comment]
Going to close until we can think of a sustainable approach here :/

**Pull request closed without merging**
