### PR TITLE
chore: auto add pull requests to project board

### PR DESCRIPTION
**Pull request by p0mvn**
Closes: #XXX

## What is the purpose of the change

This change introduces a GitHub action to automatically add pull requests to the project board.

There was no existing library available that worked well with "Projects beta" so I created jobs with going graphql queries to GitHub API.

Successful run: https://github.com/osmosis-labs/osmosis/runs/6345603614?check_suite_focus=true

## Testing and Verifying

*(Please pick one of the following options)*

This change is a trivial rework/code cleanup without any test coverage.

Queries can be tested in GitHub Graphql Explorer: https://docs.github.com/en/graphql/overview/explorer

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? no
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`?  no
  - How is the feature or change documented? not applicable

### CODE REVIEW

**Review by mattverse — COMMENTED** [review]
I'm generally curious on how this integrates with the project board. What I assume is happening is that the PR gets automatically gets added to "needs review" section, what happens if anyone reviews it? Does it automatically gets moved off the "needs review" section as well?

**Comment by p0mvn** [comment]
Once reviewed, it goes back into "In progress" status: https://github.com/orgs/osmosis-labs/projects/1/workflows/267854

Once merged, it gets closed and moves to the "Done" status

**Comment by p0mvn** [comment]
Technically, we could add another status like "Approved". However, issues and pull requests share the same statuses so it wouldn't make sense for issues.

I don't think not having an "Approved" status is a big problem for our team. Seems that all PR authors have been keeping track of their PRs and merge them, once approved.

**Comment by mattverse** [comment]
Yeah we definitely don't need a separate workflow to track "Approved"! Thanks for the explanation!

**Review by mattverse — APPROVED** [review]

**Comment by mattverse** [comment]
@p0mvn seems like some PRs trigger this ci run, some don't, (ex. https://github.com/osmosis-labs/osmosis/pull/1457 has this ci running, https://github.com/osmosis-labs/osmosis/pull/1456 wasn't) on what circumstances do they run?

**Pull request merged**
