### PR TITLE
Use tm-db master branch

### PR DESCRIPTION
**Pull request by faddat**
Closes: #XXX

## What is the purpose of the change

Working to overhaul tm-db upstream.  This should enable the use of badgerdb v3, and soon (after another update) it will allow rocksdb to work 
without manaully making a snapshot folder.

## Brief change log

* bump tm-db

## Testing and Verifying

*(Please pick one of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (yes / no) NO
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (yes / no) YES
  - How is the feature or change documented? (not applicable   /   specification (`x/<module>/spec/`)  /  [Osmosis docs repo](https://github.com/osmosis-labs/docs)   /   not documented)

### CODE REVIEW

**Comment by faddat** [comment]
NB: https://github.com/tendermint/tm-db/issues/248

**Comment by p0mvn** [comment]
Thanks for this PR @faddat . This version of `tm-db` seems to be unreleased yet. Can we wait until there is an actual release before updating it?

**Comment by faddat** [comment]
@p0mvn I don't know if there ever will be one.  

My understanding is that both the tendermint and cosmos teams would like to sunset it.

**Comment by ValarDragon** [comment]
I'm good with merging this, but if its alright I'd like us to get a smooth v9.0.0 release, and then try this out in a patch release?

**Comment by ValarDragon** [comment]
oh just read the changes in tm-db, lets just go ahead and merge this to main. I'm down to backport after an initial v9 release. 

Can go ahead and backport to v8 if someone wants to experiment with it

**Review by ValarDragon — APPROVED** [review]

**Pull request merged**
