### PR TITLE
chore(cosmwasm): fix typo

### PR DESCRIPTION
**Pull request by byeongsu-hong**
## Brief Changelog

reecovery_addr -> recovery_addr

### CODE REVIEW

**Review by mattverse — APPROVED** [review]
Thanks for the PR! ACK

**Comment by mattverse** [comment]
@byeongsu-hong  Can we update the testing binary and make the CI pass before going ahead and merging this?

**Comment by byeongsu-hong** [comment]
Sure! Will ping you after fix

**Review by mattverse — CHANGES_REQUESTED** [review]
Sweet thanks! Changing review status to `request change` for now to prevent accidental merging

**Comment by byeongsu-hong** [comment]
@mattverse Sorry for delay, will update before tomorrow comes!

**Comment by mattverse** [comment]
@byeongsu-hong no problem! Thanks!

**Comment by mattverse** [comment]
@byeongsu-hong Can we fix the merge conflicts? Then I think this should be good to go ahead and be merged

**Review by ValarDragon — APPROVED** [review]

**Comment by nicolaslara** [comment]
ahh, silly typo, thanks! The easiest way to get CI to pass is to grab the .wasm file from the artifacts (after merging main to fix conflicts)

Alternatively, if you're on an x86 machine, build with rust-optimizer 0.12.10

**Comment by byeongsu-hong** [comment]
I'm checking out to main branch and compiling now :P

**Comment by byeongsu-hong** [comment]
Seems good to merge!

**Review by mattverse — APPROVED** [review]
Sweet Thanks! Apologies for having you go through iterative merge conflicts and binary replacement

**Pull request merged**
