### PR TITLE
Ensure go v1.18 used in make build & make install

### PR DESCRIPTION
**Pull request by ValarDragon**
## What is the purpose of the change

Go 1.19 had changes that are consensus breaking. Thank you to @jhernandezb for pointing this out. This applies his suggested patch to Makefiles to ensure that all binary builds are done with the same go minor release line.

## Brief Changelog

- Require go 1.18 installed for building the binary.

## Testing and Verifying

Try building the binary if you don't have go 1.18, or build being a success if you do have go 1.18.

I've tested both

### CODE REVIEW

**Comment by faddat** [comment]
Alternative suggestion:

We should require go 1.19.  This way, there's no chance of those breaking changes cropping up because that's the latest release (no mixing of runtimes)

**Comment by ValarDragon** [comment]
I'm worried about changing to go 1.19 right now so close to release. I think in the future we should do latest minor version, but this one was tested + has binaries out with 1.18

**Review by czarcas7ic — APPROVED** [review]
ACK

**Comment by 08d2** [comment]
If some code works when compiled with Go 1.18, and breaks when compiled with Go 1.19, this represents a serious problem with that code, which needs to be fixed. Is there a summary or description of the issue?

**Comment by ValarDragon** [comment]
Oh woah, I didn't know about this! Thats really cool

**Comment by ValarDragon** [comment]
> If some code works when compiled with Go 1.18, and breaks when compiled with Go 1.19, this represents a serious problem with that code that absolutely needs to be fixed. Is there a summary or description of the problem somewhere?

So go minor versions have been known to break things at the CGO boundary numerous times often as bug patches. Its been reported that there have been crashes / breakages due to this in at least two places:

* Sort behavior has been changed. (golang sort is unstable, so the unstability altered. This is what halted persistence)
* Gzip encoding edge cases were changed, which breaks hash compatibility of state sync gossip across versions

These are both will little testing in prod thus far

**Comment by 08d2** [comment]
> Sort behavior has been changed. (golang sort is unstable, so the unstability altered . . .)

It would be a serious problem if the sort behaviors expressed by the Go stdlib API(s) broke between versions. What do you mean by `golang sort` exactly?

> Gzip encoding edge cases were changed, which breaks hash compatibility of state sync gossip across versions

Er, what? Gzip is neither deterministic nor bijective. The gzip encoding/compression of some data X has arbitrarily many representations X.gz, and arbitrarily many representations of X.gz will decode/decompress to the same data X. If there is any code which assumes otherwise, that code is broken, isn't it?

**Pull request merged**
