### PR TITLE
Fix : inconsistent proto names

### PR DESCRIPTION
**Pull request by vuong177**
Closes: #XXX

## What is the purpose of the change
 - Run `buf generate --template buf.gen.pulsar.yaml` have inconsistent proto error. 
 ```
protoc-gen-go-cosmos-orm: Go package "github.com/osmosis-labs/osmosis/api/osmosis/gamm/pool-models/balancer" has inconsistent names gammv1beta1 (osmosis/gamm/pool-models/balancer/balancerPool.proto) and balancerv1beta1 (osmosis/gamm/pool-models/balancer/tx.proto)
protoc-gen-go-grpc: Go package "github.com/osmosis-labs/osmosis/api/osmosis/gamm/pool-models/balancer" has inconsistent names gammv1beta1 (osmosis/gamm/pool-models/balancer/balancerPool.proto) and balancerv1beta1 (osmosis/gamm/pool-models/balancer/tx.proto)
protoc-gen-go-pulsar: Go package "github.com/osmosis-labs/osmosis/api/osmosis/gamm/pool-models/balancer" has inconsistent names gammv1beta1 (osmosis/gamm/pool-models/balancer/balancerPool.proto) and balancerv1beta1 (osmosis/gamm/pool-models/balancer/tx.proto)
```
 - This PR for  fix that bug.

## Brief Changelog

- Change package name in `balancerPool.proto` from `osmosis.gamm` to `osmosis.gamm.poolmodels.balancer.v1beta1`

## Testing and Verifying

This change is a trivial rework / code cleanup without any test coverage.

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (yes / no)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (yes / no) yes
  - How is the feature or change documented? (not applicable   /   specification (`x/<module>/spec/`)  /  [Osmosis docs repo](https://github.com/osmosis-labs/docs)   /   not documented)

### CODE REVIEW

**Review by mattverse — CHANGES_REQUESTED** [review]
If I remember correctly, the reason we have package inconsistency for the balancer pool is that we have to have separate migration logic since changing the proto package would cause breaking changes. I'm personally in favor of keeping this the old way (cref: https://github.com/osmosis-labs/osmosis/pull/866)

For the superfluid module, we should've had the structure of `v1beta1` in the first place, but since we didn't I don't think we should break things and change to `v1beta1` now, I'm in favor of leaving that the way it is as well, and if we need further changes using `v1beta2` and so on.

What's the possible disadvantages of leaving `buf generate --template buf.gen.pulsar.yaml` errors / is there any other possible solutions available to get around this without state breaking?

**Comment by vuong177** [comment]
> If I remember correctly, the reason we have package inconsistency for the balancer pool is that we have to have separate migration logic since changing the proto package would cause breaking changes. I'm personally in favor of keeping this the old way (cref: #866)
> For the superfluid module, we should've had the structure of `v1beta1` in the first place, but since we didn't I don't think we should break things and change to `v1beta1` now, I'm in favor of leaving that the way it is as well, and if we need further changes using `v1beta2` and so on.

Thanks for make me understand.

> What's the possible disadvantages of leaving `buf generate --template buf.gen.pulsar.yaml` errors / is there any other possible solutions available to get around this without state breaking?

I think we need fix for ORM/Pulsar support.

**Comment by mattverse** [comment]
Oh i see this is a gnarly one given the context that we had multiple fixes before as well to solve the legacy problem of proto files( https://github.com/osmosis-labs/osmosis/pull/1469) do you mind if I close this and take this one over?

**Comment by vuong177** [comment]
Yes. I close it now.

**Comment by mattverse** [comment]
thanks for bringing up this issue @vuong177  btw, we want orm support asap also for twap 🔥

**Pull request closed without merging**
