### PR TITLE
mint: change tests 

### PR DESCRIPTION
**Pull request by RusAkh**
`x/mint` tests run using `osmocli`

### CODE REVIEW

**Comment by faddat** [comment]
dude this is great!

@ValarDragon is it okay to merge into your branch?

**Comment by RusAkh** [comment]
I think it is okay as we discussed that already 👍. Shall I merge?

**Comment by ValarDragon** [comment]
I don't know that we can merge this easily unfortunately -- mint wasn't adjusted in the initial PR because mint's differences from everything else are inherited from the SDK.

So this is actually mint-CLI breaking

**Comment by ValarDragon** [comment]
Hrmm, I think we should make a github issue for breaking mint CLI.

I want to do this, we just need to get changelog set, release in a minor version and communicate to integrators.

**Pull request closed without merging**
