### PR TITLE
Remove UpdateSwapFee and SwapFeeGovernor

### LINKED ISSUE #58: Remove SwapFee Governor
This feature was removed from v0 launch roadmap.  Should be removed from the current master codebase.

### PR DESCRIPTION
**Pull request by sunnya97**
closes #58

### CODE REVIEW

**Review by ValarDragon — APPROVED** [review]
LGTM. Are we going to require pools to be re-created to specify their governance procedures later?

**Comment by sunnya97** [comment]
I suppose so.  Either these pools remain ungovernable or we use a full-chain governance proposal to decide an initial governor for them (i.e. locked LP tokens, 1 week) that they can then change.

**Comment by ValarDragon** [comment]
Hrm, maybe we should add a denom for "future governance token" in the pool definition, which could also refer to its own LP token w/ a given lockup?

**Comment by ValarDragon** [comment]
That we theres no need to go to chain governance when we enable that feature

**Comment by ValarDragon** [comment]
Per call:

Lets add a string for "Future owner". This can be an address, or a `This LP Token, lockup time` pair. We then need to build a "validate owner string" function.

Then next upgrade when we implement pool-specific governance, we automatically port the governor specification from this string.

**Pull request merged**
