### PR TITLE
fix: swagger docs & swagger generation #2233

### PR DESCRIPTION
**Pull request by ctrl-Felix**
Closes: #2233

## What is the purpose of the change

Fix the swagger API documentation

## Brief Changelog
 
  - Fix ``docs/config.json`` and add all missing protobuf files/dirs
  - Add phony tag to the Makefile for ``make docs`` to not interfere with ``/docs``
  - generate new documentation

## Testing and Verifying

Run ``make docs``

## Documentation and Release Note

I am not sure about that

### CODE REVIEW

**Review by ValarDragon — APPROVED** [review]
LGTM - though I have no idea what all this client docs are / are they even helpful

**Comment by ctrl-Felix** [comment]
> what all this client docs are / are they even helpful

The current doc is absolutely outdated. A lot of missing queries paired with not working queries:

https://api.osmosis.interbloc.org/swagger/#/

**Comment by czarcas7ic** [comment]
Thanks for doing this @ctrl-Felix! It was for sure needed for those using swagger endpoint 😄

**Review by czarcas7ic — APPROVED** [review]

**Comment by ValarDragon** [comment]
Thanks for fixing this! Let me make an issue to revisit if theres a better flow we can have as well

This makes sense to backport to v11 right?

**Review by p0mvn — APPROVED** [review]

**Comment by p0mvn** [comment]
> Thanks for fixing this! Let me make an issue to revisit if theres a better flow we can have as well
> 
> This makes sense to backport to v11 right?

I think that makes sense

**Pull request merged**
