### PR TITLE
fixed mint and burn message examples to include the to and from addresses

### PR DESCRIPTION
**Pull request by maxrobot**
## What is the purpose of the change

> Add a description of the overall background and high level changes that this PR introduces

Simply to add the `mint-to-address` and `burn-from-address` into the examples of the CLI for mint and burn tokenfactory messages.

## Testing and Verifying

This change is a trivial rework / code cleanup without any test coverage.

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes?
  - [ ] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented? 
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [x] N/A

### CODE REVIEW

**Review by pysel — APPROVED** [review]
lgtm thanks!

**Review by p0mvn — APPROVED** [review]

**Comment by p0mvn** [comment]
devbot add changelog fix tokenfactory CLI to include address parameters for mint and burn

**Comment by p0mvn** [comment]
devbot help

**Comment by devbot-wizard** [comment]
Hi! I'm DevBot, a bot that helps with common tasks in the development process. Commands:
- `devbot fix`: Fix basic errors in the PR. (e.g. imports, changelog conflicts, go mod conflicts)
- `devbot merge base`: Merge the base branch into the PR branch.
- `devbot add changelog [misc/feat/bug/api/sec] [message]`: Add a changelog entry to the PR. (e.g. `devbot add changelog feat Added a new feature`)
    - If message is blank, defaults to PR title.
- `devbot re-pr`: Re-PR the PR, useful for external contributors where we have no edit perms.

**Comment by p0mvn** [comment]
devbot add changelog bug fix tokenfactory CLI to include address parameters for mint and burn

**Comment by p0mvn** [comment]
@ValarDragon making you aware of a devbot issue^

**Comment by czarcas7ic** [comment]
@ValarDragon devbot not working because its targeting osmosis-labs:main instead of main

**Comment by ValarDragon** [comment]
You'd have to run `re-PR` it to make it work from a fork right now. We can try to make it work with forks where we have push rights

**Pull request merged**
