### PR TITLE
Fix second source of (minor) over-LP shares

### PR DESCRIPTION
**Pull request by ValarDragon**
## What is the purpose of the change

Another bug, spotted by samczun. Not caught in tests, because it occurs on uneven swap amounts.

For uneven swap amounts, we tend to have tokens remaining after doing an equal ratio swap. For each of the tokens, we do a single asset pool join.

The logic was broken in providing the correct number fo shares for single asset joins. This PR fixes it.

This change added tests and can be verified as follows:

- Breaking down logic for handling uneven swap amounts and unit testing each function separately: https://github.com/osmosis-labs/osmosis/pull/1721
- Test cases for `CalcJoinPoolShares` with uneven swap amounts: https://github.com/osmosis-labs/osmosis/pull/1713

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? yes
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? yes
  - How is the feature or change documented? not applicable

### CODE REVIEW

**Review by alexanderbez — APPROVED** [review]
Looks good so far. Are we just working on a unit test for this?

**Comment by ValarDragon** [comment]
yeah we just need unit tests

**Comment by p0mvn** [comment]
Working on unit tests and more comments here: https://github.com/osmosis-labs/osmosis/pull/1721

**Comment by p0mvn** [comment]
I think we should merge this and review https://github.com/osmosis-labs/osmosis/pull/1721 separately. What do you all think?

**Comment by stackman27** [comment]
Should #1723  be address in this PR as well?

**Comment by mattverse** [comment]
> Should #1723 be address in this PR as well?

IMO, it's definitely a fix that we need but not with this PR since stableswap is a completely different component

**Comment by p0mvn** [comment]
Going to add a changelog entry and merge.

Unit tests are coming in:
- Breaking down logic for handling uneven swap amounts and unit testing each function separately: https://github.com/osmosis-labs/osmosis/pull/1721
- Test cases for `CalcJoinPoolShares` with uneven swap amounts: https://github.com/osmosis-labs/osmosis/pull/1713

**Review by alexanderbez — APPROVED** [review]

**Pull request merged**
