### PR TITLE
Token factory documentation

### PR DESCRIPTION
**Pull request by mattverse**
Closes: #XXX

## What is the purpose of the change
Adding documentation of token factory: Leaving this as a draft since I've only added a message section for now, any ideas on documentation we can add here is welcomed

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (yes / no)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (yes / no)
  - How is the feature or change documented? (not applicable   /   specification (`x/<module>/spec/`)  /  [Osmosis docs repo](https://github.com/osmosis-labs/docs)   /   not documented)

### CODE REVIEW

**Review by Newman1515 — COMMENTED** [review]
Ok

**Comment by stackman27** [comment]
What `feeTokens` would these new tokens have? Is that worth documenting? 

Also, are we not keeping track of `x/tokenFactory` progress in #1029?

**Comment by mattverse** [comment]
Token factory is a module that allows creating, minting and burning of a new token. That being said, token factory module doesnt add any new tokens by itself, but would be rather added by the users using the token factory

**Comment by ValarDragon** [comment]
Alright if I merge this now, to not have this blocked on further updates!

**Comment by daniel-farina** [comment]
I think we should merge this, it can be updated/improved later but we need it.

**Review by ValarDragon — APPROVED** [review]

**Review by Newman1515 — COMMENTED** [review]
Ok

**Comment by Newman1515** [comment]
Go for it 👍

Sent from Yahoo Mail on Android 
 
  On Wed, May 25, 2022 at 11:22 AM, Francisco A ***@***.***> wrote:   


@Newman1515 commented on this pull request.

Ok

**Pull request merged**
