### PR TITLE
Superfluid staking PR

### PR DESCRIPTION
**Pull request by xBalbinus**
Closes: #1073

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by xBalbinus** [comment]
This PR does:

- Merges all MD files into one ginormous README for easy reading
- A brief added introduction docs to the superfluid state machine itself.

**Comment by daniel-farina** [comment]
lgtm. This closes #1073. Update PR with link to it.

**Comment by daniel-farina** [comment]
lgtm. This closes #1073. Update PR with link to it.

**Review by ValarDragon — APPROVED** [review]
The initial section is much better! I'm also a big fan of everything in a single file, I never liked the spec folder breakdown

**Pull request merged**
