### PR TITLE
Update blocked.go

### PR DESCRIPTION
**Pull request by faddat**
The US treasury dept added tornado cash addresses to the OFAC list.  I'm also going to automate the process of generating blocked.go so that we can check against it in CI, and I hope to be finished with that today.

### CODE REVIEW

**Comment by mattverse** [comment]
wdym by checking the addresses in the CI?

**Comment by faddat** [comment]
Was going to leave that to a separate PR, but basically, we've got a URL where we have a line by line list of strings.  

Can make a ci job that fails if the list is not up to date, probably some simple bash.

**Review by alexanderbez — COMMENTED** [review]
RIP (I did not confirm these addrs)

**Comment by faddat** [comment]
Agree on all fronts + cry-emoji 😢

**Comment by tacolopo** [comment]
i say delete this file instead.

**Comment by faddat** [comment]
@tacolopo make the PR, then you'll have implemented the no / no with veto option.

**Comment by ValarDragon** [comment]
Hey! Lets punt these PRs until after governance decisions.

**Pull request closed without merging**
