### PR TITLE
bug: send non osmo txfees to community pool instead of stakers

### PR DESCRIPTION
**Pull request by czarcas7ic**
Closes: #XXX

## What is the purpose of the change

Txfees collected in non osmo should be swapped to osmo at epoch and sent to the community pool. The taker fee feature implemented a new module account that collects non osmo funds, swaps them, and sends the to stakers instead. This module account was mistakenly used in the txfees logic instead of the old community pool txfees collector.

Very low impact from this bug, and simply swapping the module accounts fixes this.

### CODE REVIEW

**Comment by czarcas7ic** [comment]
devbot help

**Comment by devbot-wizard** [comment]
Hi! I'm DevBot, a bot that helps with common tasks in the development process. Commands:
- `devbot fix`: Fix basic errors in the PR. (e.g. imports, changelog conflicts, go mod conflicts)
- `devbot merge base`: Merge the base branch into the PR branch.
- `devbot add changelog [misc/feat/bug/api/sec] [message]`: Add a changelog entry to the PR. (e.g. `devbot add changelog feat Added a new feature`)
    - If message is blank, defaults to PR title.
- `devbot re-pr`: Re-PR the PR, useful for external contributors where we have no edit perms.

**Comment by czarcas7ic** [comment]
devbot add changelog bug

**Review by p0mvn — APPROVED** [review]
LGTM

**Pull request merged**
