### PR TITLE
refactor(osmoutils): remove redundant ctx param from DeleteAllKeysFromPrefix

### PR DESCRIPTION
**Pull request by p0mvn**
Closes: #XXX

## What is the purpose of the change

Removes redundant param

### CODE REVIEW

**Comment by p0mvn** [comment]
@devbot-wizard help

**Comment by devbot-wizard** [comment]
Hi! I'm DevBot, a bot that helps with common tasks in the development process. Commands:
- `devbot fix`: Fix basic errors in the PR. (e.g. imports, changelog conflicts, go mod conflicts)
- `devbot merge base`: Merge the base branch into the PR branch.
- `devbot add changelog [misc/feat/bug/api/sec] [message]`: Add a changelog entry to the PR. (e.g. `devbot add changelog feat Added a new feature`)
    - If message is blank, defaults to PR title.
- `devbot re-pr`: Re-PR the PR, useful for external contributors where we have no edit perms.

**Comment by p0mvn** [comment]
@devbot-wizard add changelog api remove redundant ctx param from DeleteAllKeysFromPrefix in osmoutils

**Review by AlpinYukseloglu — APPROVED** [review]
Hmm interesting that this made it in - I don't see any documentation explaining why this might have been intentional so presumably it's good to remove. Implementation LGTM

**Comment by nicolaslara** [comment]
👏

**Pull request merged**
