### PR TITLE
Fix markdown files using `make markdown`

### PR DESCRIPTION
**Pull request by AlpinYukseloglu**
## What is the purpose of the change

This PR tests the `make markdown` functionality added in #2630 to determine if there are any changes that need to be made and  to clean up our existing markdown files (so as to not clutter future outputs of `make markdown` or `make mdlint`)

## Brief Changelog

- Ran `make markdown`

## Testing and Verifying

This change is a trivial rework / code cleanup without any test coverage.

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (no)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (no)
  - How is the feature or change documented? (not applicable)

### CODE REVIEW

**Comment by ValarDragon** [comment]
Can this be added to `make format` as well?

**Review by ValarDragon — APPROVED** [review]

**Comment by AlpinYukseloglu** [comment]
> Can this be added to `make format` as well?

Do you think it's worth adding a docker call to make format? I originally didn't because it to avoid adding friction but if you're okay with it I'll throw it in there @ValarDragon

**Comment by AlpinYukseloglu** [comment]
> > Can this be added to `make format` as well?
> 
> Do you think it's worth adding a docker call to make format? I originally didn't because it to avoid adding friction but if you're okay with it I'll throw it in there @ValarDragon

Ended up just adding it, let me know what you think!

**Review by alexanderbez — APPROVED** [review]
❤️❤️❤️❤️

**Review by ValarDragon — APPROVED** [review]
Nice!

**Pull request merged**
