### PR TITLE
[dev-ux] Make Makefile more usable

### PR DESCRIPTION
**Pull request by mattverse**
Partially Closes: https://github.com/osmosis-labs/osmosis/issues/6494

## What is the purpose of the change
Why does make file have so much low accessibility right now

We have sufficient amount of commands in our makefile that would help us improve QOL, just that the accessibility towards the commands is pretty bad, and we often times don't utilize the commands we have to our best. 

I think a part of this stems from Makefile not being able to display available commands, like we do with the osmosis binary, where cobra would display available commands. 

This PR proposes to add a somewhat similar UX with Makefile, where we display availabe commands for each category. 
This PR only includes the `proto` category as an example, **upon this PR being approved and agreed upon, planning to make further PR for all the other available commands and categories in our current make file (e.g build, test and so on)** 

This is what the changed Makefile command looks like

```
(base) matt@MacBook-Pro osmosis % make proto
proto subcommands

Usage:
  make proto-[command]

Available Commands:
  proto-all        Run proto-format and proto-gen
  proto-gen        Generate Protobuf files
  proto-format     Format Protobuf files
  proto-image-build  Build the protobuf Docker image
  proto-image-push  Push the protobuf Docker image
```

## Testing and Verifying

This change is a trivial rework / code cleanup without any test coverage.

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes?
  - [ ] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented? 
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [ ] N/A

### CODE REVIEW

**Review by p0mvn — APPROVED** [review]
Nice

**Review by pysel — APPROVED** [review]
cool!

**Comment by czarcas7ic** [comment]
I also think this is really nice, just as a side note though, if you enable auto complete for the CLI it also works for Makefile commands! I still see value in this though and agree its cool, approving and merging!

**Comment by czarcas7ic** [comment]
@mattverse Do you think we can create a CI job, where if someone adds a Makefile command and it doesn't include the help description, it errors? That would be the final piece to ensure this stays relevant

**Comment by mattverse** [comment]
Good point, I'll take a look to see if such is possible and include it in the next PR if so. Thanks for the recommendation!

**Pull request merged**
