### PR TITLE
chore: Remove docs folder

### PR DESCRIPTION
**Pull request by niccoloraspa**
## What is the purpose of the change

Since we have moved the docs to their own [repository](https://github.com/osmosis-labs/docs) 
I think we can remove the `docs` folder and free some space at the top level of the repo.

## Brief Changelog

- Remove `docs/` folder

## Testing and Verifying

This change is a trivial rework / code cleanup without any test coverage.

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? no
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? no
  - How is the feature or change documented? not applicable

### CODE REVIEW

**Comment by ValarDragon** [comment]
The proto docs are auto generated, but I don't understand whose the consumer of them.

I am personally happy to delete them, but we should put some effort into understanding if anyone else uses them.
cc @marbar3778

**Comment by marbar3778** [comment]
we deleted them in the sdk. we upload to but schema registry that handles this like godocs https://buf.build/cosmos/cosmos-sdk/docs/main:cosmos.app.v1alpha1

**Review by p0mvn — APPROVED** [review]

**Comment by ValarDragon** [comment]
@niccoloraspa can you delete them from wherever they're generated? (Should be somewhere in make proto-all)

**Comment by niccoloraspa** [comment]
I did look into this a little more.

The auto-generate proto stuff is in `clients/docs`.
There is a `make docs` command that runs `./scripts/generate-docs.sh` that updates the content of that `clients/docs` folder. 

```bash
❯ make docs

=========== Generate Message ============

./scripts/generate-docs.sh
```

script: https://github.com/osmosis-labs/osmosis/blob/main/scripts/generate-docs.sh


---------

Regarding the `docs` folder removed here. 
There is a `DevDoc` section in the Makefile that generates the content of the `docs` folder:

```bash
###############################################################################
###                                 Devdoc                                  ###
###############################################################################

build-docs:
	@cd docs && \
	while read p; do \
		(git checkout $${p} && npm install && VUEPRESS_BASE="/$${p}/" npm run build) ; \
		mkdir -p ~/output/$${p} ; \
		cp -r .vuepress/dist/* ~/output/$${p}/ ; \
		cp ~/output/$${p}/index.html ~/output ; \
	done < versions ;

sync-docs:
	cd ~/output && \
	echo "role_arn = ${DEPLOYMENT_ROLE_ARN}" >> /root/.aws/config ; \
	echo "CI job = ${CIRCLE_BUILD_URL}" >> version.html ; \
	aws s3 sync . s3://${WEBSITE_BUCKET} --profile terraform --delete ; \
	aws cloudfront create-invalidation --distribution-id ${CF_DISTRIBUTION_ID} --profile terraform --path "/*" ;
.PHONY: sync-docs
```

I will remove this section from the Makefile but I propose to address the proto stuff in another issue/PR.

**Review by ValarDragon — APPROVED** [review]

**Pull request merged**
