### PR TITLE
chore(version): update all references from v7 to v8

### PR DESCRIPTION
**Pull request by PaddyMc**
## What is the purpose of the change

Unable to import "github.com/osmosis-labs/osmosis/v8@8.0.0"

This error happens as there is a mismatch between go.mod (module github.com/osmosis-labs/osmosis/v7) and the tagged version (v8.0.0)

The error occurs when trying to use the latest version of osmosis in golang applications, specifically the issue found was

```
no concrete type registered for type URL /osmosis.superfluid.MsgUnPoolWhitelistedPool against interface *types.Msg
```

with the suggested change in this PR updating to the latest version would fix this issue.

## Brief Changelog

  - Updating go.mod and imports to specify the correct verison, this will fix clients 

## Testing and Verifying

This change is a trivial rework / code cleanup without any test coverage.

How to test:

I created a PR on a fork to demonstrate the fix, https://github.com/PaddyMc/osmosis/tree/chore/update-version:

```bash
~/ mkdir test                  
~/ cd test                 
~/ touch main.go  
~/ go mod init github.com/test/test                                               
go: creating new go.mod: module github.com/test/test
go: to add module requirements and sums:
	go mod tidy

~/ go get github.com/osmosis-labs/osmosis/v7@v8.0.0
go get: github.com/osmosis-labs/osmosis/v7@v8.0.0: invalid version: module path includes a major version suffix, so major version must match

~/ go get github.com/osmosis-labs/osmosis/v8@v8.0.0
go get: github.com/osmosis-labs/osmosis/v8@v8.0.0: invalid version: go.mod has non-.../v8 module path "github.com/osmosis-labs/osmosis/v7" (and .../v8/go.mod does not exist) at revision v8.0.0

~/  go get github.com/osmosis-labs/osmosis/v7@v7.0.3
go: downloading github.com/osmosis-labs/osmosis/v7 v7.0.3
go get: added github.com/osmosis-labs/osmosis/v7 v7.0.3
 
~/ go get github.com/PaddyMc/osmosis/v8@2960480c2e86b3091b80ceb4a72ff1eb434cb7db
go: downloading github.com/PaddyMc/osmosis/v8 v8.0.0-20220527150925-2960480c2e86
go: added github.com/PaddyMc/osmosis/v8 v8.0.0-20220527150925-2960480c2e86
```

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (`no`)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (`no`)
  - How is the feature or change documented? ([Osmosis docs repo](https://github.com/osmosis-labs/docs))

### CODE REVIEW

**Comment by ValarDragon** [comment]
Thanks for this PR! really appreciate it. Looks great to me

**Review by ValarDragon — APPROVED** [review]

**Comment by ValarDragon** [comment]
Oh wait this is targetting main, I thought it was going to v8.

We should go ahead and update main to v9 directly (release very soon for it) However will likely hold off a couple days on that since it will break every open PR

**Comment by PaddyMc** [comment]
The release branch has the correct version it seems, the issue is that the tag happened before the version update, I think releasing a new v8.0.1 tag should fix the issue. :muscle: 

PR: https://github.com/osmosis-labs/osmosis/pull/1513

TAG:
```
commit e4c86d4add32d4d9d83337ae7ed90c3b822b5503
Merge: 16e3b51f 59b59b53
Author: Dev Ojha <ValarDragon@users.noreply.github.com>
Date:   Mon May 16 20:12:43 2022 +0200

    Merge pull request #1513 from osmosis-labs/roman/update-paths-v8
    
    chore: upgrade package paths to v8 on v8.x

commit 16e3b51f19a58f815a4eabcbcee11886eb33e026 (tag: v8.0.0)
Merge: 45ac35ae 6f140b38
Author: Dev Ojha <ValarDragon@users.noreply.github.com>
Date:   Sun May 15 08:19:58 2022 +0200

    Merge pull request #1481 from osmosis-labs/mattverse/gov-unpool
    
    v8 Emergency proposals upgrade
```

go.mod: https://github.com/osmosis-labs/osmosis/blob/v8.x/go.mod#L1

**Comment by ValarDragon** [comment]
ah sweet, I'll just go ahead and tag v8.0.1 right after merging https://github.com/osmosis-labs/osmosis/pull/1611 !

**Comment by ValarDragon** [comment]
Done! Sorry about that

**Comment by PaddyMc** [comment]
aceeee! thanks :bow:

**Pull request closed without merging**
