### PR TITLE
refactor(SQS): convert poolmanager taker fee calc methods to functions

### PR DESCRIPTION
**Pull request by p0mvn**
Closes: https://app.clickup.com/t/86a1af4tp

## What is the purpose of the change

This PR converts some poolmanager taker fee calc methods to functions. In https://github.com/osmosis-labs/osmosis/pull/6785, these are used in SQS calculations directly.

### CODE REVIEW

**Review by AlpinYukseloglu — APPROVED** [review]
LGTM, nice catch/cleanup

**Review by mattverse — COMMENTED** [review]
LGTM

**Comment by p0mvn** [comment]
@Mergifyio refresh

**Comment by p0mvn** [comment]
@mergifyio refresh

**Pull request merged**
