### PR TITLE
feat: streamswap implementation

### PR DESCRIPTION
**Pull request by robert-zaremba**
Implementation for x/streamswap (moving from the old osmolbp branch).

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (yes / no)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (yes / no)
  - How is the feature or change documented? (not applicable   /   specification (`x/<module>/spec/`)  /  [Osmosis docs repo](https://github.com/osmosis-labs/docs)   /   not documented)

### CODE REVIEW

**Comment by robert-zaremba** [comment]
Spec will be added later today or tomorrow.

**Comment by p0mvn** [comment]
Hi @robert-zaremba . Thank you for this change. Would you be able to please split this PR up into smaller components to ease and speed up the review process? 

We could probably start by splitting up `types` and `osmoutils` into another PR. What do you think?

**Comment by robert-zaremba** [comment]
Here is the spec: https://github.com/osmosis-labs/osmosis/pull/2605

**Comment by robert-zaremba** [comment]
@p0mvn OK - I will remove other files and leave `types` and `osmoutils` in this PR.

**Comment by robert-zaremba** [comment]
I've removed keeper and module implementation in this PR

**Comment by p0mvn** [comment]
From the latest updates, streamswap is not planned to be pursued as a Go module so I'm going to close this for now. Thank you @robert-zaremba and please let me know if any concerns

**Comment by robert-zaremba** [comment]
All good, thanks @p0mvn

**Pull request closed without merging**
