### PR TITLE
Move fork and upgrade logic into sub-directory structure

### PR DESCRIPTION
**Pull request by ValarDragon**
Cref: #671 

## Description

Pull request for trying to re-arranging around the fork and migration code. This moves them, to their own sub-directory.

I mainly did this to play around with some of the code structure here. The main bottleneck was import cycles due to app.go, and having to pass around keepers instead of the app.

I suggest we keep this structure, and then make a second "AppKeepers" struct, which actually stores all of the keepers. Then OsmosisApp stores a reference to an AppKeepers struct that we pass to all of these migration logics.

I think these sub-folders for each upgrade will make it easier to track old upgrade code, and keep a reasonable location to have it be commented out, without cluttering an important file like app.go.

Thoughts?

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Review by UnityChaos — APPROVED** [review]
Full support on the idea, utAck on the implementation. Looks good to me, but we should probably try to test it somehow?
I think the idea of separating out each upgrade and then eventually commenting them out once the code is no longer logically reachable makes sense.

Also interesting that the v6 upgrade has essentially no contact with this refactor, because it does no actual state migrations.

**Comment by ValarDragon** [comment]
Good point, this should have tests before we go through it. I'll write a test for v3 and v5 upgrades. (I'll do this by checking the parameters set during the upgrade)

**Comment by ValarDragon** [comment]
Committed a test that updates the v4 upgrade keeper. (It reinstates an old test with mild adjustments, that got deleted in #538 ) This shows that the keeper reference setup is generally working here.

The thing thats not tested is adding new stores during an upgrade, but thats really essentially the same as what exists right now

**Comment by ValarDragon** [comment]
Proceeding with merge, since Unity approved, and test added.

**Pull request merged**
