### PR TITLE
chore: add markdown linter

### PR DESCRIPTION
**Pull request by p0mvn**
Closes: #1210

## What is the purpose of the change

Adding a markdown linter to bring all to promote consistency in the codebase.

GitHub Action used: https://github.com/github/super-linter
Linter that the action uses: https://github.com/igorshubovych/markdownlint-cli

## Brief change log

- adding the ci job
- fixed auto-fixable  issues locally
- enabled the linter in ci to only run on diffs, not the entire repository

## Testing and Verifying

This change is a trivial rework/code cleanup without any test coverage.

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? no
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? no
  - How is the feature or change documented? not applicable

### CODE REVIEW

**Review by alexanderbez — APPROVED** [review]
TYSM @p0mvn 🙏

**Comment by p0mvn** [comment]
@alexanderbez Unfortunately, there seem to be a lot of issues that cannot be fixed automatically. Looks like several hours of manual work. 

I'm keeping this open as a draft to decide how to go about this. What do you think?

I don't mind spending the time if we all feel that the linter is useful. However, judging by the discussions in #1210, this might not worth the effort

**Comment by ValarDragon** [comment]
I'll adapt if you and Bez want it!

**Comment by alexanderbez** [comment]
@p0mvn why not just add a bunch of rules to ignore that cause a lot of the headache? Then, we can slowly uncomment/remove the ignored rules piece-meal? I'd be happy to help you on this

**Comment by p0mvn** [comment]
@alexanderbez Sounds good. Thanks for the suggestion. I will keep this PR open until I get to it

**Comment by p0mvn** [comment]
Closing in favor of https://github.com/osmosis-labs/osmosis/pull/1478

**Pull request closed without merging**
