### PR TITLE
Add release pipeline to create artifacts for osmosis releases

### PR DESCRIPTION
**Pull request by nikever**
Continues: #1550 

## What is the purpose of the change

This PR introduces an automatic release workflow via GitHub Actions to create all the artifacts for an osmosis release.
This workflow runs on every new tag or when manually triggered and it creates a release folder with all the osmosis binaries as workflow output.

## Brief Changelog

- Introduce automatic release workflow via GitHub Actions

## Testing and Verifying

Tested this workflow on a fork: https://github.com/nikever/osmosis/actions/runs/2422822418
The release folder is present in the `Artifacts` section:

image

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? no
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? no
  - How is the feature or change documented? not applicable

### CODE REVIEW

**Review by alexanderbez — COMMENTED** [review]
Does this use goreleaser behind the scenes?

**Comment by nikever** [comment]
Not currently, the script creates all the release files manually.

We could switch to goreleaser but we need the PRO version as we would need a custom build process which afaik is not available in the free version.

**Review by ValarDragon — APPROVED** [review]
LGTM! I'm not quite sure that goreleaser helps us any tbh, docker file seems great

**Comment by nikever** [comment]
I feel the same way, `goreleaser` won't add much at the moment.

We would still need to use this Docker process to create the binaries and then add `goreleaser` after it.

**Pull request merged**
