### PR TITLE
Test suites refactor

### PR DESCRIPTION
**Pull request by catShaark**
Closes: #1148

## Description
I try to put all the necessary test suite logic of modules into apptesting package, like @ValarDragon describing in #1148

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by catShaark** [comment]
So I put some the logic commonly used in all the modules test, put them into method of KeeperTestHelper, I also add test accounts as a field in KeeperTestHelper to replace acc1, acc2, acc3 in keeper_test.go

**Review by alexanderbez — APPROVED** [review]

**Comment by ValarDragon** [comment]
Thanks so much for making this! Reviewing now

**Comment by ValarDragon** [comment]
Oh, I wasn't sure about the usage of the static addresss list that was changed in a lot of the tests. Let me make a separate issue for that then

**Comment by catShaark** [comment]
> Oh, I wasn't sure about the usage of the static addresss list that was changed in a lot of the tests. Let me keep investigating that issue then.
> 
> Basically `suite.TestAccs[0]` being used instead of acc1, and if thats safe or not

The suite.TestAccs[] thing is inspired from `ibc-test`'s `testchain` where they store the account and its key to do action on the `testchain`, also some helper code in `apptesting` like func `PrepareBalancerPoolWithPoolParams` needs to have a `pool creating account` that is accessible to `gamm`'s `suite` so that the main reason I create `TestAccs` . 

> 
> I guess if the policy is that all re-usable helper code should use new temporary keys, it could be fine?

**Pull request merged**
