### PR TITLE
refactor[CL]: rename `PrecisionFactorAtPriceOne` to `ExponentAtPriceOne`

### PR DESCRIPTION
**Pull request by pysel**
Closes: #4748 

## What is the purpose of the change

Better dev-UX

## Testing and Verifying

N/A

## Documentation and Release Note

N/A

### CODE REVIEW

**Review by p0mvn — APPROVED** [review]

**Comment by czarcas7ic** [comment]
Hey, I wasn't aware of this issue, but IMO the standard should be `PrecisionFactorAtPriceOne` instead of `exponentAtPriceOne`

**Comment by mattverse** [comment]
I stand by this re-name, exponent at price one seems like a more intuitive naming for me compared to precision factor at price one.

> Hey, I wasn't aware of this issue, but IMO the standard should be `PrecisionFactorAtPriceOne` instead of `exponentAtPriceOne`

@czarcas7ic  Is there a reason you prefer `PrecisionFactorAtPriceOne`?

**Comment by czarcas7ic** [comment]
My conviction on the name isn't that strong, happy to go with the exponent name since you all agree!

**Review by mattverse — APPROVED** [review]

**Comment by pysel** [comment]
> My conviction on the name isn't that strong, happy to go with the exponent name since you all agree!

hey @czarcas7ic, my point is to use one name for the same thing throughout the repo to prevent confusions with the name, but I think I agree with you that `PrecisionFactorAtPriceOne` is a better name. 

ofc it is up to you guys to pick the final name, I only want to prevent naming confusions

CC: @mattverse @p0mvn

**Comment by stackman27** [comment]
one simple nit that i noticed is that we haven't added [exponent-at-price-one] as a part of tx use field [here](https://github.com/osmosis-labs/osmosis/blob/main/x/concentrated-liquidity/client/cli/tx.go#L30)

can we please add it create-concentrated-pool [denom-0] [denom-1] [tick-spacing] [exponent-at-price-one] [swap-fee]

**Comment by p0mvn** [comment]
> one simple nit that i noticed is that we haven't added [exponent-at-price-one] as a part of tx use field [here](https://github.com/osmosis-labs/osmosis/blob/main/x/concentrated-liquidity/client/cli/tx.go#L30)
> 
> can we please add it so that it looks like this;
> 
> ```
> create-concentrated-pool [denom-0] [denom-1] [tick-spacing] [exponent-at-price-one] [swap-fee]
> ```

@pysel can you please address this, and then we can merge this

**Comment by czarcas7ic** [comment]
Added the comment, will merge once passes CI

**Comment by pysel** [comment]
> Added the comment, will merge once passes CI

oh, apologies for a long response, thank you @czarcas7ic for adding!

**Pull request merged**
