### PR TITLE
chore: port x/gov

### PR DESCRIPTION
**Pull request by alexanderbez**
Closes: #2481

## Brief Changelog

* Port x/gov from osmosis' fork of the Cosmos SDK from the `osmosis-main` branch.

### CODE REVIEW

**Comment by alexanderbez** [comment]
This might be trickier than I originally thought, mainly because of external modules, e.g. x/params, that rely on cosmos-sdk repo x/gov.

**Comment by ValarDragon** [comment]
Oh yikes, would we have to import this as an independent go.mod, and then do a replace in our main go.mod?

**Comment by ValarDragon** [comment]
On skim, seems like its only these gov handlers that are the problem, which if so, we should be able to make a function that takes in an SDK type handler and returns an osmosis gov type handler?

**Comment by alexanderbez** [comment]
Jumping back on this...

**Comment by alexanderbez** [comment]
@ValarDragon after updating the import paths to `github.com/osmosis-labs/osmosis/v11/x/gov`, we get more build errors and the wiring just becomes to messy, mainly in tests where we use simapp for testing (which makes no sense to me)

**Comment by ValarDragon** [comment]
Closing in favor of #2854 

I think we can update the tests in a second pass

**Pull request closed without merging**
