### PR TITLE
Dynamically generated IBCAliases map

### PR DESCRIPTION
**Pull request by pysel**
- add assetlist.json
- add script to parse assetlist
- enable caching
- mod sum

Related to: https://github.com/osmosis-labs/osmosis/issues/3655
## Changes
This PR introduces a map: `denom -> ibc_denom`. assetlist.json is the same as https://github.com/osmosis-labs/assetlists/blob/main/osmosis-1/osmosis-1.assetlist.json. However, for some reason I could not import it, so I just simply added it to the project. 
## Documentation
not documented yet

### CODE REVIEW

**Comment by ValarDragon** [comment]
Hrmm, I like this, except for having to vendor the assetlist in the repo :/

**Comment by RusAkh** [comment]
> Hrmm, I like this, except for having to vendor the assetlist in the repo :/

yeah I also do not like that, but I could not think of a different approach, wdyt?

**Comment by ValarDragon** [comment]
I also don't like the idea of introducing a security critical dependency to assetlists, under a different maintenance structure. Maybe we:
* ship with something hardcoded and trimmed
* make a command to generate from assetlist (and that script live downloads assetlist into your home repo)

**Comment by RusAkh** [comment]
hello @ValarDragon. I found a way to read assetlist. This is kind of a "lol" way to do it: 
- read it from GitHub in python and create a file
- parse file in Golang
- then delete file from Golang 
If you are ok with this approach we can leave it like that, so we do not need to bring the whole `assetlist.json` to repo

**Comment by p0mvn** [comment]
Hi @pysel . Is there anything that needs to be done here? AFAIU, the conclusion was to pursue an approach via smart contracts for solving this. If you are in agreement, can we close this?

**Comment by pysel** [comment]
yeah, guess so

**Pull request closed without merging**
