### PR TITLE
Fix update import paths workflow

### PR DESCRIPTION
**Pull request by pysel**
Part of: #5391 

## What is the purpose of the change

- [x] Fix regex for getting `version_to_replace`
Fixes the logic for getting `version_to_replace` from the list of go modules (`go list -m`). It used to search for pattern `g.*v` and save a string after the `v` symbol. Before `epochs` became a standalone module, it worked, because the path with the version (aka `github.com/osmosis-labs/osmosis/vX`) was printing at the end of the list, so saving everything after `v` worked. 
After epochs have been added, the same logic returned `X github.com/osmosis-labs/osmosis/x/epochs` and saved it to `version_to_replace`. This issue can be seen in this run: https://github.com/osmosis-labs/osmosis/actions/runs/5115321530/jobs/9222845233

- [x] Do not automatically update paths in go.mods, which explicitly reference some version of previous version ([example](https://github.com/osmosis-labs/osmosis/blob/main/tests/cl-go-client/go.mod#L8))
As this is an urgent matter, I suggest we merge this PR, run the workflow, and then manually update `tests/cl-genesis-positions` and `tests/cl-go-client`, but I want to also add reminder into the body of created PR that some paths might need manual update

## Testing and Verifying

Manually tested that new regex results in correct `version_to_create`

## Documentation and Release Note
N/A

### CODE REVIEW

**Comment by pysel** [comment]
for reviewers: https://github.com/osmosis-labs/osmosis/issues/5391#issuecomment-1573037376

CC: @p0mvn @stackman27

**Comment by pysel** [comment]
PR that was created by the run of the workflow: https://github.com/osmosis-labs/osmosis/pull/5403

CC: @stackman27 @p0mvn

**Review by p0mvn — APPROVED** [review]
Thanks for the quick PR sir! Any suggestions on how we can fix `cl-go-client` and avoid manual updates in the future?

**Comment by pysel** [comment]
> Thanks for the quick PR sir! Any suggestions on how we can fix `cl-go-client` and avoid manual updates in the future?

I will create a separate issue to discuss this matter

**Pull request merged**
