### PR TITLE
Add gas config to the client.toml

### PR DESCRIPTION
**Pull request by hieuvubk**
Closes: #4962 

## What is the purpose of the change

Save `gas`, `gas-prices`, `gas-adjustment` into `client.toml`. So user no more needs to pass gas flags in cmd, it will get data from config.

## Brief Changelog
- Overwrite `ConfigCmd`
- Use `OsmosisCustomClient ` instead of `ClientConfig`: the purpose is to integrate some of the fields mentioned above
- The config fields will be set & get directly on the client.toml file

## Flow
- You can configure `gas` or any field with the command
`osmosisd config gas 1000000`
- Run tx cmd, no need to pass `gas` flag more. Its will get data that saved in `client.toml`
- If user wanna change they config, use `osmosisd config [key] [value]`

### CODE REVIEW

**Comment by faddat** [comment]
@hieuvubk can you please add a changelog to this pr?

**Review by faddat — APPROVED** [review]
looks good, once it's got a changelog!

heh, gotcha covered on it :)

**Comment by czarcas7ic** [comment]
@hieuvubk has this been compiled and tested locally?

**Comment by hieuvubk** [comment]
> @hieuvubk has this been compiled and tested locally?

yes, I tested in my locally, can write & cmd can read data from `client.toml`. 
One thing I wanna to ask, should we config `fees` cause I see all tx cmd need at least one fee denom.

**Comment by czarcas7ic** [comment]
@hieuvubk yeah that would be great, please ping when that has been added and tested against mainnet and I will merge!

**Comment by hieuvubk** [comment]
@czarcas7ic Fees added, this is my test tx against mainnet using `osmosisd tx bank send from to 100000uosmo --from key` without any flag. 
https://www.mintscan.io/osmosis/txs/87887D790741A45E495E3C5AB3CD89E49AC1BB906994B820B7D54C68624A86C3

**Comment by czarcas7ic** [comment]
@hieuvubk will merge as soon as you get sim to pass!

**Comment by hieuvubk** [comment]
@czarcas7ic  It passed after rerunning. Seem st wrong in the last run

**Review by czarcas7ic — APPROVED** [review]

**Comment by czarcas7ic** [comment]
Nice work @hieuvubk , merging!

**Pull request merged**
