### PR TITLE
chore: Revert min spot price changes

### PR DESCRIPTION
**Pull request by DongLieu**
Closes: #6831

## What is the purpose of the change

> Add a description of the overall background and high level changes that this PR introduces

*(E.g.: This pull request improves documentation of area A by adding ....*

## Testing and Verifying

*(Please pick one of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added unit test that validates ...*
  - *Added integration tests for end-to-end deployment with ...*
  - *Extended integration test for ...*
  - *Manually verified the change by ...*

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes?
  - [ ] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented? 
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [ ] N/A

### CODE REVIEW

**Comment by DongLieu** [comment]
Reference from PR #6682

**Review by mattverse — APPROVED** [review]
Awesome! Forgot about this, thank you :)

**Comment by mattverse** [comment]
@DongLieu Can you check if the original PR was in the changelog and if so remove it from the log?

**Review by p0mvn — APPROVED** [review]
Confirmed that changes match https://github.com/osmosis-labs/osmosis/pull/6682/files

**Comment by p0mvn** [comment]
@DongLieu could check the failing test please?

**Comment by DongLieu** [comment]
ok, i'm handling it

**Pull request merged**
