### PR TITLE
chore: update gov metadata length from 256 to 10200

### PR DESCRIPTION
**Pull request by PaddyMc**
## What is the purpose of the change

Update the metadata length to 10200, to enable longer summaries and titles for gov proposals

see:
https://github.com/osmosis-labs/cosmos-sdk/blob/osmo/v0.47.5/x/gov/keeper/proposal.go#L17-L32

&&

https://github.com/osmosis-labs/cosmos-sdk/blob/osmo/v0.47.5/x/gov/keeper/keeper.go#L222-L229

## Testing and Verifying

- start a node and submit a gov transaction with longer metadata

```bash
BASE64_METADATA=$(echo -n '{
	"authors": [""],
	"details": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
	"proposal_forum_url": "",
	"vote_option_context": ""
}' | base64 -w 0)

echo '{
  "messages": [
    {
      "@type": "/cosmos.bank.v1beta1.MsgSend",
      "from_address": "'"$GOVMODULEACC"'",
      "to_address": "'$ADDRESS1'",
      "amount": [{"denom": "uosmo", "amount": "1000000"}]
    }
  ],
  "metadata": "'"$BASE64_METADATA"'",
  "deposit": "3000000000uosmo",
  "title": "My Latest pro proposal",
  "summary": "A short summary of my proposal",
  "expedited": true
}' > proposal.json

# submit-proposal: Submit a proposal along with some messages, metadata and deposit
tx_result=$(osmosisd tx gov submit-proposal proposal.json $OPTS $SENDER -y --output json | jq .txhash)
echo $tx_result 
```

## Documentation and Release Note

  - [x] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented? 
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [x] Code comments?
  - [ ] N/A

### CODE REVIEW

**Review by mattverse — APPROVED** [review]
ACK

**Comment by mattverse** [comment]
On the second thought, do you think this change should be fine in terms of state size increase? ( I think this should be fine.. just wanted to mention for sanity check before we merge this!)

**Comment by PaddyMc** [comment]
> On the second thought, do you think this change should be fine in terms of state size increase? ( I think this should be fine.. just wanted to mention for sanity check before we merge this!)

This just returns the value to what it was pre-0.47.x upgrade :+1:

**Review by ValarDragon — APPROVED** [review]

**Comment by ValarDragon** [comment]
yeah its just 10kb

**Pull request merged**
