### PR TITLE
makefile: add target to run `go mod tidy` in all submodules

### PR DESCRIPTION
**Pull request by pysel**
Closes: #6531 

## What is the purpose of the change

Add a makefile target that runs a script that tidies all submodules by parsing go.work file. To run the script, cd into the root of the repository and run `make tidy-workspace`

In addition, this PR includes the changes made by this new target

## Testing and Verifying

Manually tested, changes included in this PR

## Documentation and Release Note
 Changelog

### CODE REVIEW

**Comment by pysel** [comment]
> **Important Notice**
> 
> This PR modifies an in-repo Go module. It is one of:
> 
> * osmomath
> * osmoutils
> * x/ibc-hooks
> * x/epochs
> 
> The dependent Go modules, especially the root one, will have to be updated to reflect the changes. Failing to do so might cause e2e to fail.
> 
> Please follow the instructions below:
> 
> 1. Open https://github.com/osmosis-labs/osmosis/actions/workflows/go-mod-auto-bump.yml
> 2. Provide the current branch name
> 3. On success, confirm if an automated commit corretly updated the go.mod and go.sum files
> 
> Please let us know if you need any help.

Ignoring since the changes in submodules are the updates of go modules themselves

**Comment by pysel** [comment]
devbot add changelog feat makefile: add target that tidies all submodules at once

**Review by mattverse — COMMENTED** [review]
Do you know why go.mod would have changed by any chance?

**Review by p0mvn — APPROVED** [review]
Nice! Would be great to add this to devbot CC: @ValarDragon

**Review by mattverse — APPROVED** [review]
utACK! Thanks for the quick PR!

**Pull request merged**
