### PR TITLE
Faster CI for contracts

### PR DESCRIPTION
**Pull request by nicolaslara**
## What is the purpose of the change

Make it easier to compile the x86 contracts on CI

## Brief Changelog

 - Only running the optimizer once

## Testing and Verifying
CI should pass
## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (/ no)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (/ no)
  - How is the feature or change documented? (not applicable )

### CODE REVIEW

**Comment by ValarDragon** [comment]
can we add some comments to this, I don't really understand it tbh, I imagine next editor will have similar problems

**Comment by nicolaslara** [comment]
sorry, yeah, this is not done. I'll make it a draft

**Comment by nicolaslara** [comment]
My objective here is to execute the optimize and upload artifacts steps only once per workdir, but then check all the diffs. 

My initial experiments are not working, so I'll move on and come back to this later

**Comment by nicolaslara** [comment]
I'm gonna close this for now. Need to revisit this eventually. Added an issue to track it: https://github.com/osmosis-labs/osmosis/issues/4123

**Comment by nicolaslara** [comment]
I'm gonna close this for now. Need to revisit this eventually. Added an issue to track it: https://github.com/osmosis-labs/osmosis/issues/4123

**Pull request closed without merging**
