### PR TITLE
chore: Use label for code-rabbit activation

### PR DESCRIPTION
**Pull request by mattverse**
Closes: #XXX

## What is the purpose of the change
Created a label `request-code-rabbit-review` where only with the label, code rabbit will review. 

## Testing and Verifying

*(Please pick one of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added unit test that validates ...*
  - *Added integration tests for end-to-end deployment with ...*
  - *Extended integration test for ...*
  - *Manually verified the change by ...*

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes?
  - [ ] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented?
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [ ] N/A

### CODE REVIEW

**Review by czarcas7ic — APPROVED** [review]
<3333333333

**Review by PaddyMc — APPROVED** [review]
:rabbit:

**Comment by ValarDragon** [comment]
I would actually really like not doing this personally.

**Comment by czarcas7ic** [comment]
We can probably close this now that code rabbit has calmed tf down lol

**Pull request closed without merging**
