### PR TITLE
fix: fix the typo of response field "recovery_addr"

### PR DESCRIPTION
**Pull request by Halimao**
## What is the purpose of the change

fix the typo of response field "recovery_addr"

### CODE REVIEW

**Review by pysel — APPROVED** [review]

**Review by mattverse — APPROVED** [review]
Thanks for the PR! LGTM

**Comment by mattverse** [comment]
@Halimao Cosmwasm contract CI  seems to be failing, can you recompile contract and replace the wasm file in  artifacts/crosschain_swaps.wasm?

**Comment by Halimao** [comment]
> @Halimao Cosmwasm contract CI seems to be failing, can you recompile contract and replace the wasm file in artifacts/crosschain_swaps.wasm?

Hi @mattverse wasm files were updated

**Comment by mattverse** [comment]
@Halimao Awesome thanks so much! :)

**Pull request merged**
