### PR TITLE
Make token factory handle empty genesis configurations better

### PR DESCRIPTION
**Pull request by ValarDragon**
## What is the purpose of the change

A problem @czarcas7ic ran into was getting panics on token factory messages, when the genesis wasn't initialized.

## Brief Changelog

- Improve nil handling of token factory InitGenesis

## Testing and Verifying

- TODO

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? yes
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? no, still pre-release for token factory
  - How is the feature or change documented? not applicable, removes a thing to document tbh

### CODE REVIEW

**Comment by ValarDragon** [comment]
e2e test failure seems like some sort of docker issue?

**Comment by czarcas7ic** [comment]
The local compilation is not hitting blocks, so essentially the update failed. I will go through it locally to see what the specific issue is for this pr

**Review by czarcas7ic — APPROVED** [review]

**Review by alexanderbez — COMMENTED** [review]
Curious why it'd ever be nil to begin with. Does default genesis state not use `sdk.NewCoins`?

**Comment by czarcas7ic** [comment]
I ran into it when modifying the v8 genesis on LocalOsmosis to work on v9. Will the average user ever run into this case? Probably not. But its just a nice check to have since if it is null (like it was in my case) and it still gets through init genesis, it causes untraceable errors.

**Comment by alexanderbez** [comment]
We should add safe guards, I agree @czarcas7ic 👍

**Pull request merged**
