### PR TITLE
[E2E] Add ParseEvent function

### PR DESCRIPTION
**Pull request by phamminh0811**
Closes: #5601
## What is the purpose of the change
Create a helper ParseEvent function to minimize duplication.

## Testing and Verifying

This change is already covered by existing tests.

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes?
  - [ ] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented? 
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [ ] N/A

### CODE REVIEW

**Comment by phamminh0811** [comment]
@ThanhNhann I tried to looking for some parse event function but I can only find out GetPositionId which is need to get the events. Do you think is helper function is helpful?

**Comment by ThanhNhann** [comment]
Refer to discuss [link](https://github.com/osmosis-labs/osmosis/pull/4690/files#r1230818024), so we will have some parse event functions like `GetPositionID` @phamminh0811

**Review by ThanhNhann — APPROVED** [review]
LGTM!

**Review by p0mvn — APPROVED** [review]
LGTM

**Review by pysel — APPROVED** [review]
lgtm!

**Review by ValarDragon — APPROVED** [review]
nice! Good incremental step

(To get multi-message support, we'll then adapt this to scope to scanning things by msg_index later. TBD how thats done, I'd guess maintaining a "first_index_to_look_at_next" would work)

**Pull request merged**
