### PR TITLE
chore: fix every typo that ever exists on the repo

### PR DESCRIPTION
**Pull request by hoangdv2429**
Closes: #XXX

## What is the purpose of the change

> Add a description of the overall background and high level changes that this PR introduces

This PR will fix every typo that exists on Osmosis

## Testing and Verifying

*(Please pick one of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes?
  - [ ] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented? 
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [ ] N/A

### CODE REVIEW

**Comment by hoangdv2429** [comment]
Add another CI and we will have typo no more.

**Comment by hoangdv2429** [comment]
let's not touch the contracts for now.

**Comment by hoangdv2429** [comment]
@czarcas7ic Can you review this one ?

**Comment by czarcas7ic** [comment]
@hoangdv2429 are we able to implement a CI job instead of manually fixing these?

**Comment by hoangdv2429** [comment]
@czarcas7ic yes we can, but to do so we also need a list of to be ignore folders and words. I encountered lots of it when working on this one.

**Review by mattverse — APPROVED** [review]
I'm supportive of merging this for now then implementing the CI job in separate PR

**Comment by czarcas7ic** [comment]
I had to drop CI due to competing requirements, please feel free to pick up if you have time

**Pull request merged**
