### PR TITLE
chore: set optimistic execution

### PR DESCRIPTION
**Pull request by czarcas7ic**
Closes: #XXX

## What is the purpose of the change

As requested by @ValarDragon

### CODE REVIEW

**Review by ValarDragon — APPROVED** [review]

**Comment by ValarDragon** [comment]
Actually since this is state compat, maybe we should get v26.0.0 without this, and v26.1.0 with it?

**Comment by czarcas7ic** [comment]
@ValarDragon I was told by Facu from Binary Builders that the feat does nothing without 2/3 voting power on it.

We can add in minor but I don't think there is a high likelyhood of getting voting power on it without a manual push

(msg here https://osmosis-network.slack.com/archives/C047X1T6ERK/p1718615619678329?thread_ts=1718492283.495959&cid=C047X1T6ERK)

**Review by PaddyMc — APPROVED** [review]
:zap:

**Comment by czarcas7ic** [comment]
Lets keep this open until v26.0.0 is out and then merge, as per Dev's request.

**Comment by tac0turtle** [comment]
you should be able to test this on mainnet today allowing you to track performance

**Pull request merged**
