### PR TITLE
add CLI query poolmanager params

### PR DESCRIPTION
**Pull request by DongLieu**
Closes: #6349

## What is the purpose of the change

add CLI query and testing for poolmanager params

## Testing and Verifying

*(Please pick one of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added unit test that validates ...*
  - *Added integration tests for end-to-end deployment with ...*
  - *Extended integration test for ...*
  - *Manually verified the change by ...*

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes?
  - [ ] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented? 
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [ ] N/A

### CODE REVIEW

**Comment by pysel** [comment]
hey @DongLieu! could you please attach required labels and add this to changelog? thanks!

**Comment by DongLieu** [comment]
added

**Review by mattverse — APPROVED** [review]

**Comment by mattverse** [comment]
@DongLieu Seem's like proto CI is failing, can you try proto-genning off of current branch? If it still fails, try merging to main then generating!

**Comment by p0mvn** [comment]
This was merged in https://github.com/osmosis-labs/osmosis/pull/6441

**Pull request closed without merging**
