### PR TITLE
Update init.go to increase max outbound peers for validator nodes

### PR DESCRIPTION
**Pull request by bfritton**
Change to max outbound peers for validator node as requested by Valardragon and proposed by FONDSMATIVE and dff | mp20

### CODE REVIEW

**Review by ValarDragon — APPROVED** [review]
LGTM! Just going to leave open for a day or so, to check if any other folks would like to opine. I think this is long term too high, but probably useful short term.

My reasoning is that with high numbers of peers being saturated on the peerlist, increasing the number of outbound connections you try makes sense. And when the p2p network reforms each epoch, you retry connecting to more peers. 

(Granted Tendermint p2p is complex, and I may be misunderstanding this!)

**Comment by faddat** [comment]
I'd say "do not merge".

I recently made a PR on Tendermint itself and the key to my logic was changing the ratio:

I went from previous default (10 outbound and 40 inbound)

to 

new default (20 outbound and 160 inbound)

the goal is to have peers gettin all promiscuous.  In the p2p layer, we want them connecting, lots.

**Comment by ValarDragon** [comment]
Should we be updating the defaults here to those settings Jacob?

**Comment by faddat** [comment]
Yes, I should have made a PR to his branch.

I'll do that now.

**Comment by faddat** [comment]
40 and 320 actually seem more appropriate for us.  

The network has always seemed kind of choked.

**Comment by faddat** [comment]
@bfritton I'm sorry I slowed this down!


Have been super busy lately.  Surely, we needed to change these settings.

❤️

**Pull request merged**
