### PR TITLE
go work sync

### PR DESCRIPTION
**Pull request by faddat**
## What is the purpose of the change

This PR is me running go work sync, and when I did that a number of go.mod 
and go.sum files were changed.  The repository passes tests, so I have 
assumed that this is "a good thing"TM. Please close this if not desired. 

## Brief Changelog

`go work sync`

## Testing and Verifying

This is a highly trivial change unworthy of a change to the changelog. 

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior 
changes? no
  - Is a relevant changelog entry added to the `Unreleased` section in 
`CHANGELOG.md`? yes
  - How is the feature or change documented? not applicable

### CODE REVIEW

**Comment by faddat** [comment]
changelog reminder ftw

**Comment by faddat** [comment]
(force pushed to remove two unnecessary commits that should have gone on another branch)

**Comment by p0mvn** [comment]
@faddat merged main here and removed changelog entry while doing so because the change is not client facing. Hope you don't mind

Will merge this in as soon as CI passs. Thank you

**Comment by p0mvn** [comment]
Actually, it looks like this change has already gotten in with your other PR: https://github.com/osmosis-labs/osmosis/pull/5065

Making this obsolete after merging main. As a result, going to close this. Please let me know if something isn't right here

**Pull request closed without merging**
