### PR TITLE
Cli module query params

### PR DESCRIPTION
**Pull request by najeal**
Closes: #8460 

## What is the purpose of the change

This pull request add missing params query for modules used in `osmosisd q`

## Testing and Verifying

This change added tests and can be verified as follows:

  - Added unit test that validates : incentives params request result

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes?
  - [x] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented?
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [x] N/A

### CODE REVIEW

**Comment by najeal** [comment]
@czarcas7ic This is a draft of what I have understand about the issue. If it is mostly about you are expecting I'll continue to add params queries for the other modules.

**Comment by czarcas7ic** [comment]
I'm on mobile but at glance this looks like what is desired, thanks!

**Comment by najeal** [comment]
@mattverse I see you have closed and reopened the PR. Did I do something wrong?

Changelog does not pass -> I let you decide if a new line must be added or not.
protobuf and e2e tests fail -> it is caused by docker and git authentication. I assume it is because you must trigger if manually.

**Comment by czarcas7ic** [comment]
No, we do it to trigger our CI when it gets stuck

**Review by mattverse — APPROVED** [review]
I like this! LGTM

**Comment by mattverse** [comment]
@najeal Can you add changelog entry please? 🙏

**Comment by najeal** [comment]
@mattverse I added new entry into `Unreleased -> State Compatible`

**Comment by mattverse** [comment]
Thanks @najeal seems like there is a merge conflict to resolve as well, can  you go ahead and fix it?

**Comment by najeal** [comment]
@mattverse conflict resolution has been done 👍

**Pull request merged**
