### PR TITLE
gorocksdb

### PR DESCRIPTION
**Pull request by faddat**
## Description

This is a simple fix that makes osmosis work properly with rocksdb. 

#695 

 It also bumps:

* Tendermint to v0.34.15
* tm-db to v0.6.6

______

For contributor use:

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [x] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [x] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Review by ValarDragon — APPROVED** [review]
LGTM! I'll fix merge conflicts with marko's PR for removing replaces and get it merged

**Comment by ValarDragon** [comment]
Can you give me write access to PRs to main 😅

**Comment by ValarDragon** [comment]
There maybe some wierd things for allowing maintainers to commit to an organization. If so, can you just cherry-pick thee two commits:
```
df19a2f3d505ae1196fa8bbcb86b621ab91385f9
9bdac4f57e6a61ed36afaaa1b517688938522539
```

and we can get it merged?

**Comment by ValarDragon** [comment]
going to push fix in second branch, so it gets in! I imagine your stacked in other things rn

**Comment by faddat** [comment]
oh hey sorry!

thank you!

**Pull request closed without merging**
