### PR TITLE
refactor(osmomath): replace Power with PowerInteger

### PR DESCRIPTION
**Pull request by p0mvn**
Progress towards: #3540 

## What is the purpose of the change

I missed the existence of `Power` when adding `PowerInteger`. As a result, these functions are identical.

I propose removing the old `Power` and replace all calls with `PowerInteger` since I am adding a new `Power` function that takes a decimal exponent.

**Note:**
- The removed `Power` is identical with `PowerInteger`
- The existing `PowerInteger` tests include and cover all removed test cases.

### CODE REVIEW

**Comment by ValarDragon** [comment]
This LGTM, but it should be state compatible and backportable?

**Comment by p0mvn** [comment]
> This LGTM, but it should be state compatible and backportable?

Agreed. Sorry I confused it with this `Pow` that is used in cfmm and erred on the side of caution:
https://github.com/osmosis-labs/osmosis/blob/d69dd69f0251c12077ca2bda8f085e389d58c9fd/osmomath/math.go#L57

**Comment by p0mvn** [comment]
Labels are now changed

**Review by ValarDragon — APPROVED** [review]
LGTM!

**Pull request merged**
