### PR TITLE
Added module dependence graph

### PR DESCRIPTION
**Pull request by xBalbinus**
Closes: #1635 

## What is the purpose of the change

As per the comment originally posted by @ValarDragon in #1621 

We should make a visual dependency graph of the Osmosis modules in the x/README.md file.

## Brief Changelog

Added a module dependency graph in the x/README.md file

## Testing and Verifying

**This change is a trivial rework / code cleanup without any test coverage.**

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (yes / **no**)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (yes / **no**)
  - How is the feature or change documented? (**not applicable**   /   specification (`x/<module>/spec/`)  /  **[Osmosis docs repo]**(https://github.com/osmosis-labs/docs)   /   not documented)

### CODE REVIEW

**Review by mattverse — COMMENTED** [review]
Awesome! Did we decide not to go with drawing the specified dependencies of gamm module? ( How pool-models package and gamm packages are related etc.) imo that's one of the places with the most module dependency complexity that would be nice to have the dependency graph on

**Comment by xBalbinus** [comment]
Ah, I should probably go deeper on that then. Will revise & send a copy on by to you on slack, this is just a temporary edit / will be modified

**Comment by ValarDragon** [comment]
I'm a bit worried about this being unmaintainable. Is there a way to make a link or source file other people can edit to update this in the future?

**Comment by xBalbinus** [comment]
Yep, there is a way to make an editable copy - I exported the drawing as a loadable file (for future editing) that I will add to this PR

**Comment by ValarDragon** [comment]
Suggestions:
* Remove cfmm_internal - It has internal in the name!
* Change Balancer tag line as "constant product AMM"
* Change Stableswap tag line to just "stableswap AMM"
* Change Gamm module tag line to "Swap, LP & CreatePool messages"
* Change Superfluid staking tag line to "Allow Defi assets containing osmo to be used in staking"
* Change epochs tag line to "On-chain timers, allowing modules to execute code once/day"

**Comment by ValarDragon** [comment]
For Balancer and Stableswap, by chanigng the tag lines I meant the sub-text for it, its imo too long in the summary diagram. Balancer and Stableswap as the heading was good

**Comment by ValarDragon** [comment]
Rendered link: https://github.com/osmosis-labs/osmosis/blob/xiangan/moddepgraph/x/README.md

Can we also reduce the vertical space used here?

**Comment by ValarDragon** [comment]
Does anything come to mind for how to increase readability of the smaller text in the bubbles?

Beyond that, LGTM

**Comment by xBalbinus** [comment]
I will be back after some dinner to try to make it less verbose and enlarge
the text / play with the formatting!

**Review by ValarDragon — APPROVED** [review]
I like the new version!

**Pull request merged**
