### PR TITLE
from Int{} to ZeroInt() balancer pool

### PR DESCRIPTION
**Pull request by RusAkh**
Closes: #2615 

## What is the purpose of the change

For the sake of cleanness returns in balancer/pool.go now return sdk.ZeroInt()

## Brief Changelog
Same as purpose

## Testing and Verifying

Changed value in TestJoinPool -> after that all current tests passed

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? No
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? No
  - How is the feature or change documented? no

### CODE REVIEW

**Review by AlpinYukseloglu — APPROVED** [review]
LGTM!

**Review by p0mvn — APPROVED** [review]

**Review by mattverse — COMMENTED** [review]
Thanks for this PR! Glad that we brought this topic up!

I personally would prefer the other way around, where we would change existing zeroints to Int{}. The reason for this is because although we would have error catchers on the callers, I think we double ensure saftey for this within the method by returning a empty struct. IMO using zero int values can lead to using the zero value as the actual value in some cases.

Thoughts? cc. @AlpinYukseloglu @p0mvn

**Comment by ValarDragon** [comment]
I'm not a fan of this, and don't understand why we would change this behavior.

**Comment by p0mvn** [comment]
Thanks for the PR @RusAkh . Based on the discussions, we would like to instead be returning `sdk.Int{}` in similar cases so I'm going to close this

**Pull request closed without merging**
