### PR TITLE
fix: cl spotprice query

### PR DESCRIPTION
**Pull request by doggystylez**
Closes: #XXX

## What is the purpose of the change

fixed inconsistency in spot price query for cl pools - the base and quote denoms are being reversed due to the spot price querier providing them in reverse order:
https://github.com/osmosis-labs/osmosis/blob/c26756d897641ee441070986d898e72f94f47807/x/poolmanager/client/query_proto_wrap.go#L151

and edited spot price cli command help text to reflect actual behavior of "denom in, denom out"

note - I also noticed that the path for this query doesn't include the v1beta1 version name
https://github.com/osmosis-labs/osmosis/blob/c26756d897641ee441070986d898e72f94f47807/proto/osmosis/poolmanager/v1beta1/query.proto#L70-L72

## Testing and Verifying

This change modified the spotprice test to swap the args and can be verified as follows:

  - *Manually verified the change by ...*
  - query spot price for cl pool at `<lcd>/osmosis/poolmanager/pools/1066/prices?base_asset_denom=uosmo&quote_asset_denom=ibc/0CD3A0285E1341859B5E86B6AB7682F023D03E97607CCC1DC95706411D866DF7`

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes?
  - [ ] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented? 
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [ ] N/A

### CODE REVIEW

**Comment by doggystylez** [comment]
upon futher investigation, this affects and reverse the twap for cl pools also, making this state breaking

**Review by mattverse — COMMENTED** [review]
I think we should have it along with the twap fix we need to make (by twap fix, I'm referring to the twap record that this change will cause break. We would either need migration or removal of the existing twap record)

**Review by AlpinYukseloglu — APPROVED** [review]
LGTM once changelog entry is added. We should also create a follow-up issue for migrating/deleting existing records as discussed internally.

**Review by czarcas7ic — APPROVED** [review]
This looks good, appreciate the PR!

**Pull request merged**
