### PR TITLE
Add a v7 upgrade handler

### PR DESCRIPTION
**Pull request by ValarDragon**
## Description

Add v7 upgrade handler

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Review by mattverse — COMMENTED** [review]
Haven't took a look at superfluid module yet, just curious if superfluid module does not have to go inside `CreateUpgradeHandler`!

**Comment by ValarDragon** [comment]
Yeah, migration logic for superfluid does have to be added. At the moment it will do superfluid.InitGenesis(superfluid.DefaultGenesis()).

This should be fixed in a separate PR though

**Review by mattverse — APPROVED** [review]
Ah I see! Question solved! LGTM!

**Comment by ValarDragon** [comment]
Thanks for the quick review!

**Pull request merged**
