### PR TITLE
Add param to allow non lock owner to force unlock

### PR DESCRIPTION
**Pull request by iboss-ptk**
## What is the purpose of the change

To allow an account to forcibly unlock any lock, including ones they do not own, if their address is on the whitelist. This functionality is needed for [transmigrator](https://github.com/osmosis-labs/transmigrator)

## Brief Changelog

  - Add `NonOwnerForceUnlockAddresses` to lockup params
  - By pass ownership check in `ForceUnlock` if  msg sender is in `NonOwnerForceUnlockAddresses`

## Testing and Verifying

This change added tests and can be verified as follows:
  - Added unit test that validates if msg sender is in NonOwnerForceUnlockAddresses
    - they can force unlock their own locks 
    - they can force unlock their other's locks 

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (no)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (no)
  - How is the feature or change documented? (not documented)

### CODE REVIEW

**Comment by ValarDragon** [comment]
What is the precise permission we need to expose, this feels too permissive to expose

**Comment by iboss-ptk** [comment]
@ValarDragon the contract needs to be able to:

unlock -> exit pool -> swap -> join pool -> lock

While retaining deposit period & needs to get everything unlocked locked back in some form.

The problem with existing approach is that if we authz ForceUnlock, `msg.Owner` will be the user not the contract. If we can get authz `MsgExec` sender somehow (which is the contract in this case), that might be better approach since it can be more restrictive. I'm not sure if that is possible.

**Comment by mattverse** [comment]
feels like authz is a more preferrable way than using this method to me, @iboss-ptk  do you need help on further investigation if this is possible?

**Comment by iboss-ptk** [comment]
@mattverse That would be helpful! I'm a bit lost in getting `MsgExec` sender info without modifying existing `MsgForceUnlock`. If there is a way for that, that would be ideal.

**Comment by sunnya97** [comment]
@mattverse I don't see how authz would help here.  Cause normal users don't have ability to force unlock, so they can't authz the ability to do that either

**Comment by sunnya97** [comment]
TODO:  Allow breaking of superfluid as well

**Comment by p0mvn** [comment]
@iboss-ptk are we still planning to pursue this? If not, let's close.

**Pull request closed without merging**
