### PR TITLE
add annotations for client tooling and codegen

### PR DESCRIPTION
**Pull request by pyramation**
## What is the purpose of the change

This adds new annotations used by codegen tools to create encoders/decoders that can manage the `google.protobuf.Any` types. This change has many (positive) implications:

### RPC calls get properly decoded

Currently, when you do an RPC call, for example,

```
const request: QueryPoolsRequest;
const result = await osmosis.gamm.v1beta1.pools(request);
```

In the current system, you get back results that just have a bunch of encoded bytes (not very useful for FE devs):

```
{
  "pools": [
    {
        "typeUrl": "/osmosis.gamm.v1beta1.Pool",
        "value": <a bunch of bytes>
    },
    {
        "typeUrl": "/osmosis.gamm.v1beta1.Pool",
        "value": <a bunch of bytes>
    },
    ...
    {
        "typeUrl": "/osmosis.gamm.poolmodels.stableswap.v1beta1.Pool",
        "value": <a bunch of bytes>
    }
  ]
}
```

Leveraging the `implements_interface` and `accepts_interface`, we can now derive and generate decoders, in this case, the pools:

```js
export const PoolI_InterfaceDecoder = (input: _m0.Reader | Uint8Array): Pool1 | Pool2 | Any => {
  const reader = input instanceof _m0.Reader ? input : new _m0.Reader(input);
  const data = Any.decode(reader, reader.uint32());

  switch (data.typeUrl) {
    case "/osmosis.gamm.v1beta1.Pool":
      return Pool1.decode(data.value);

    case "/osmosis.gamm.poolmodels.stableswap.v1beta1.Pool":
      return Pool2.decode(data.value);

    default:
      return data;
  }
};
```

This will now give us the expected API result when fetching pools (and will also [close issues like this one](https://github.com/osmosis-labs/osmojs/issues/5) and [make people like Larry0x happy](https://twitter.com/larry0x/status/1597307451640270849?s=20&t=V6xZP0B0cXEa60ftI4cyqA))

### Messages with nested messages/protos and their amino encoders for ledger support

Additionally, we can create encoders for toAmino/fromAmino that leverage interfaces with proper annotations. Here is an example for proposals that multiplex on `content` using the `Content` interface:

- [`fromAmino` encoder](https://gist.github.com/pyramation/2946ecd3d497f1b3f00ee0bb24824ef8)
- [`toAmino` encoder](https://gist.github.com/pyramation/38f7c198274872f67e97732a21d3e074)

This can enable a new class of dApps built on osmosis. Currently developers have to manually construct all of these encodings.

### importing `amino/amino.proto`
- [ ] we need to be able to import `amino/amino.proto` which currently exists in the [cosmos/cosmos-sdk](https://github.com/cosmos/cosmos-sdk/tree/main/proto/amino)
- [ ] issue in osmosis-labs/cosmos-sdk [is here](https://github.com/osmosis-labs/cosmos-sdk/issues/400)

### Missing codec registrations

These are missing amino registrations (via `RegisterConcrete`):
- [ ] `MsgExtendLockup`
- [ ] `MsgForceUnlock`
- [ ] `MsgRedelegateValidatorSet`

These are missing amino registration (via `RegisterConcrete`), but registered via `RegisterProposalTypeCodec`:

- [ ] `ReplacePoolIncentivesProposal` (osmosis/ReplacePoolIncentivesProposal)
- [ ] `SetProtoRevAdminAccountProposal`
- [ ] `SetProtoRevEnabledProposal`

#### convention for `Register*` names (amino/proposal/etc)

should we have a convention for `Register*` names? I noticed some discrepancies:

- [ ] `osmosis/SetSuperfluidAssetsProposal` for `RegisterProposalTypeCodec` vs `osmosis/set-superfluid-assets-proposal` for `RegisterConcrete`
- [ ] `osmosis/UpdatePoolIncentivesProposal` is used for BOTH `RegisterProposalTypeCodec` and `RegisterConcrete`

#### interface conventions

- [ ] determine [how we're going to annotate interfaces](https://github.com/cosmos/cosmos-sdk/discussions/10368#discussioncomment-4439985)

Once we resolve that conversation, we can determine if we need to do this

```diff
-  option (cosmos_proto.implements_interface) = "cosmos.gov.v1beta1.Content";
+ option (cosmos_proto.implements_interface) = "Content";
```

## Brief Changelog
 
  - *imports `amino/amino.proto`* (which means this PR needs to be rebased BEFORE merge, [issue here](https://github.com/osmosis-labs/cosmos-sdk/issues/400))
  - *adds interface annotations*
  - *adds amino annotations*

## Testing and Verifying

This change added tests and can be verified as follows:

  - *should NOT affect Go compilation (to my knowledge)*
  - *was tested locally for tranpilation/codegen with Telescope*

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? NO — not for Go or Cosmos SDK side of things.

### CODE REVIEW

**Comment by faddat** [comment]
I'm of the opinion that it is important to make Larry happy!

You mentioned that this would be aided by adding annotations to the osmosis-sdk, right?

**Comment by pyramation** [comment]
> I'm of the opinion that it is important to make Larry happy!
> 
> You mentioned that this would be aided by adding annotations to the osmosis-sdk, right?

yep! this depends on importing `amino/amino.proto`, which is a new proto that exists in the [cosmos/cosmos-sdk](https://github.com/cosmos/cosmos-sdk/tree/main/proto/amino). I've raised an issue in osmosis-labs/cosmos-sdk [is here](https://github.com/osmosis-labs/cosmos-sdk/issues/400)

**Review by ValarDragon — APPROVED** [review]
Looks great to me! I'll do the proto builds

**Comment by ValarDragon** [comment]
ah wait no, we need to update our SDK to have `amino.proto` first.

**Comment by pyramation** [comment]
> ah wait no, we need to update our SDK to have `amino.proto` first.

yep, issue documented here, will comment over there now https://github.com/osmosis-labs/cosmos-sdk/issues/400

**Review by mattverse — APPROVED** [review]
Do we have any test that has been done to ensure that this way of amino encoding / decoding ensures compatibility with the old way of handling amino? 

Otherwise LGTM, but lets hold merging until https://github.com/osmosis-labs/cosmos-sdk/issues/400 has been pushed forward

**Comment by pyramation** [comment]
> Do we have any test that has been done to ensure that this way of amino encoding / decoding ensures compatibility with the old way of handling amino?

There is not a test, but as far as I understand it, this is only annotations for fields, `option (amino.name)`. No Go code should be affected. Maybe @amaurym or @tac0turtle can comment more about the impact these annotations as they're aware of the new proto annotations.

> Otherwise LGTM, but lets hold merging until [osmosis-labs/cosmos-sdk#400](https://github.com/osmosis-labs/cosmos-sdk/issues/400) has been pushed forward

Cool!

**Comment by tac0turtle** [comment]
this will not effect go code since the generator doesn't account for it. It will be part of the proto descriptor that clients can use though

**Comment by pyramation** [comment]
let's not mark this as stale or old, thanks!

**Comment by pyramation** [comment]
let me know if we can make this PR happen, or if I need to rebase and make a new one, thanks!

**Comment by pyramation** [comment]
hey @mattverse — the last PR adds the amino file, right? Which means we likely can add this PR soon.

**Comment by mattverse** [comment]
hey @pyramation yeah! working on porting your changes over right now

**Comment by mattverse** [comment]
@pyramation Would you mind if I close this PR and open a new PR that includes these changes? Need some additional updates in go.mod and compile protobuf files as well

**Comment by pyramation** [comment]
> @pyramation Would you mind if I close this PR and open a new PR that includes these changes? Need some additional updates in go.mod and compile protobuf files as well

whatever works! sounds good!

**Comment by mattverse** [comment]
@pyramation  sweet! Closing this in favor of https://github.com/osmosis-labs/osmosis/pull/4629

**Pull request closed without merging**
