### PR TITLE
feat: remove osmo multihop discount

### PR DESCRIPTION
**Pull request by czarcas7ic**
Closes: #6373 

## What is the purpose of the change

Actions remaining part of [prop 530](https://www.mintscan.io/osmosis/proposals/530)

>For multi-hop swaps, this would remove the “osmo multi-hop discount”, and charge the taker fee for every pool.

Taker fees are already implemented. We just need to remove the multi-hop discount

## Testing and Verifying

Much of this PR is removing the specific osmo multi-hop discount logic/tests.

Kept some osmo incentivized multi hop pools in the tests to ensure the discount is no longer applied.

## Documentation and Release Note

  - [x] Does this pull request introduce a new feature or user-facing behavior changes?
  - [x] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented? 
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [ ] N/A

### CODE REVIEW

**Comment by czarcas7ic** [comment]
devbot help

**Comment by devbot-wizard** [comment]
Hi! I'm DevBot, a bot that helps with common tasks in the development process. Commands:
- `devbot fix`: Fix basic errors in the PR. (e.g. imports, changelog conflicts, go mod conflicts)
- `devbot merge base`: Merge the base branch into the PR branch.
- `devbot add changelog [misc/feat/bug/api/sec] [message]`: Add a changelog entry to the PR. (e.g. `devbot add changelog feat Added a new feature`)
    - If message is blank, defaults to PR title.
- `devbot re-pr`: Re-PR the PR, useful for external contributors where we have no edit perms.

**Comment by czarcas7ic** [comment]
devbot add changelog feat

**Review by p0mvn — APPROVED** [review]
LGTM

**Review by mattverse — APPROVED** [review]
LGTM! Nice work!

@czarcas7ic Do you think it makes sense to have a single test case with Base Denom: showing that base denom does not account for multihop doscount before having this merged?

**Pull request merged**
