### PR TITLE
Fix v44 auth upgrade bug

### PR DESCRIPTION
**Pull request by ValarDragon**
Workaround for https://github.com/cosmos/cosmos-sdk/issues/10591 , https://github.com/provenance-io/provenance/blob/407c89a7d73854515894161e1526f9623a94c368/app/upgrades.go#L86-L122

Just do auth upgrade last.

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by robert-zaremba** [comment]
This look as a dirty hack. I'm thinking about changing the map value type to a structure with priority.

**Comment by robert-zaremba** [comment]
Let's continue the discussion in the SDK issue

**Comment by ValarDragon** [comment]
Seeing as this is being tested on vega upgrade as well, merging

**Comment by robert-zaremba** [comment]
sure, was only saying that it's feels hacky, but solves the problem. In 0.44 we don't have other solution which is not breaking :/ except the patch for x/auth.

So your one is the best so far. I have created a draft PR for 0.45 to change the structure.

**Comment by ValarDragon** [comment]
ah 100% agreed, its absolutely a gross workaround lol

**Pull request merged**
