### PR TITLE
v3.x matinenance

### PR DESCRIPTION
**Pull request by faddat**
Works towards: #788 

## Description

This PR fixes some issues with osmosis importing v1.0 series code into its v3 self.

It also:

* bumps to tendermint v0.34.15
* bumps to tm-db v0.6.6
* adds support for gorocksdb via cosmos/gorocksdb

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by mattverse** [comment]
Thanks for this! 
Just out of curiosity, is this PR unfinished or draft, or is there a particular reason why certain imports do not have updated sem-ver?

**Comment by faddat** [comment]
Sorry, that's a bug

**Comment by faddat** [comment]
closing this to make from a branch here

**Comment by mattverse** [comment]
@faddat Oh was this waiting on me for review or was in WIP?

**Pull request closed without merging**
