### PR TITLE
chore: lint tests and sync for app, osmomath, tests, and wasmbinding

### PR DESCRIPTION
**Pull request by faddat**
Works toward: #5061 

## What is the purpose of the change

* #5127 began to become pretty unruly, and it seemed best to remove some things from it (the not-challenging, not 
type assertion things)

## Testing and Verifying

This code should pass all tests.

## Documentation and Release Note

To my knowledge, we don't want a PR like this one to hit the changelog.

Where is the change documented? 
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [x] N/A

### CODE REVIEW

**Review by mattverse — APPROVED** [review]
LGTM

**Review by hieuvubk — APPROVED** [review]
LGTM

**Comment by faddat** [comment]
One day we will conquer #5061

**Comment by p0mvn** [comment]
Merging since there are 2 approvals. Only skimmed myself. Thanks everyone

**Pull request merged**
