### PR TITLE
refactor(incentives): remove redundant param from CreateGaugeRefKeys

### PR DESCRIPTION
**Pull request by p0mvn**
Closes: #XXX

## What is the purpose of the change

Removes redundant param. Will backport and test for state compatibility

### CODE REVIEW

**Comment by p0mvn** [comment]
@devbot-wizard help

**Comment by devbot-wizard** [comment]
Hi! I'm DevBot, a bot that helps with common tasks in the development process. Commands:
- `devbot fix`: Fix basic errors in the PR. (e.g. imports, changelog conflicts, go mod conflicts)
- `devbot merge base`: Merge the base branch into the PR branch.
- `devbot add changelog [misc/feat/bug/api/sec] [message]`: Add a changelog entry to the PR. (e.g. `devbot add changelog feat Added a new feature`)
    - If message is blank, defaults to PR title.
- `devbot re-pr`: Re-PR the PR, useful for external contributors where we have no edit perms.

**Comment by p0mvn** [comment]
devbot add changelog api remove redundant param from CreateGaugeRefKeys in incentives

**Review by AlpinYukseloglu — APPROVED** [review]
Nice, LGTM!

**Pull request merged**
