### PR TITLE
JoinPool gas test

### PR DESCRIPTION
**Pull request by mattverse**
## Description

This PR includes adding gas test for join pool in the gamm module, with the recent notice of gas increase for JoinPool - aiming to prevent further increase of gas in the JoinPool logic.

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by ValarDragon** [comment]
Thanks! Can we also have a test for it where we create a new pool & new denom for every test. Thats the main thing we want to ensure doesn't grow in the new update code.

**Comment by ValarDragon** [comment]
We can also merge this, and do that second test in a later PR if you're working on other things.

**Comment by mattverse** [comment]
Nope! It's fine! Currently working on this, planning to push it within today

**Review by ValarDragon — APPROVED** [review]
LGTM, thanks for adding the test case! Different approach from what I had in mind, but this one totally works!

**Pull request merged**
