### PR TITLE
feat: allow alternate denoms for protocol fees

### PR DESCRIPTION
**Pull request by czarcas7ic**
Closes: #XXX

## What is the purpose of the change

We currently denominate protocol fees (Pool Creation, Create Gauge, Add To Gauge) in OSMO. This requires constant rebalancing when the price of OSMO fluctuates. We should instead denominate protocol fees in USD, and then extrapolate what this means in terms of any whitelisted token, and take that from the user account.

For this first version, the USD value is translated to OSMO and OSMO is taken from the user's account, but it should be a few line change to the API to allow the user to specify any whitelisted token they want to pay for these protocol fees in. 

## Testing and Verifying

List gotests that prove it is working

## Documentation and Release Note

  - [x] Does this pull request introduce a new feature or user-facing behavior changes?
  - [x] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented? 
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [ ] N/A

### CODE REVIEW

**Comment by czarcas7ic** [comment]
devbot help

**Comment by devbot-wizard** [comment]
Hi! I'm DevBot, a bot that helps with common tasks in the development process. Commands:
- `devbot fix`: Fix basic errors in the PR. (e.g. imports, changelog conflicts, go mod conflicts)
- `devbot merge base`: Merge the base branch into the PR branch.
- `devbot add changelog [misc/feat/bug/api/sec] [message]`: Add a changelog entry to the PR. (e.g. `devbot add changelog feat Added a new feature`)
    - If message is blank, defaults to PR title.
- `devbot re-pr`: Re-PR the PR, useful for external contributors where we have no edit perms.

**Comment by czarcas7ic** [comment]
devbot add changelog feat

**Comment by czarcas7ic** [comment]
closing to keep the PR list down but keeping track in my notes for when we decided to implement / becomes more priority

**Pull request closed without merging**
