### PR TITLE
Wasm custom messages

### PR DESCRIPTION
**Pull request by ethanfrey**
Adds support for `OsmosisMsg::Swap`. `MintTokens will be a future PR.

Done: Implementations
Todo: Tests

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by nicolaslara** [comment]
@ethanfrey I see you closed this without merging. Are there plans to handle wasm custom messages differently to this implementation? If so, could you point me to a branch?

**Comment by ethanfrey** [comment]
We are working on this on our fork. When it is in a good state, we will rebase and make a pr on osmosis.

Since we work on a fork, I keep accidentally making prs on osmosis.

**Comment by ethanfrey** [comment]
Expect a proper pr for osmosis to review sometime next week

**Comment by nicolaslara** [comment]
wonderful! thanks for the quick reply :)

**Pull request closed without merging**
