### PR TITLE
Make goreleaser-cross the default way to build binaries with docker

### PR DESCRIPTION
**Pull request by niccoloraspa**
## What is the purpose of the change

This PR refactors the "docker" build process of the Makefile deprecating old build targets, and introducing new ones that leverage goreleaser for building binaries.

### Changes

- Deprecated `build-reproducible`, `build-reproducible-amd64`, and `build-reproducible-arm64` targets. Now, a deprecation message will be displayed when these targets are used.
- Added new targets `goreleaser-build-darwin-amd64`, `goreleaser-build-darwin-arm64`, `goreleaser-build-linux-amd64`, and `goreleaser-build-linux-arm64`. These targets use GoReleaser to build the binaries for specific OS/architecture combinations.
- Introduced a `goreleaser-build` target that builds a binary for the user's current architecture.

## Testing and Verifying

1. Pull the changes from this PR.
2. Run `make goreleaser-build` to build a binary for your current architecture.
3. Run `make goreleaser-build-darwin-amd64` or any of the new targets to build for a specific OS/architecture.
4. Try running one of the deprecated targets to see the deprecation message.

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes?
  - [ ] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented? 
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [x] N/A

### CODE REVIEW

**Comment by niccoloraspa** [comment]
I like using goreleaser as it standardizes the way we build binaries.

From the tool:

```bash
❯ goreleaser build --help
The `goreleaser build` command is analogous to the `go build` command, in the sense it only builds binaries.

Its intended usage is, for example, within Makefiles to avoid setting up ldflags and etc in several places. 
That way, the GoReleaser config becomes the source of truth for how the binaries should be built.
```

The good things:
- Automatically uses the right go version according to the `go.mod` 
- Automatically uses the right libwasm version 

Bad things:
- We don't use `goreleaser` CLI directly but we use `goreleaser-cross` to cross-compile for different architecture and statically link the binary against the binary and therefore we require `docker` present.

**Comment by niccoloraspa** [comment]
Reopening this, found a solution to the problem I had with goreleaser.

**Comment by niccoloraspa** [comment]
Nvm, this is blocked unless we have goreleaser pro

**Comment by Lazar955** [comment]
Hi @niccoloraspa, did you manage to get the goreleaser working? I also have `libwasmvm_muslc.x86_64.a` as dependency needing to link

**Pull request closed without merging**
