### PR TITLE
add flowcharts images to README.md in tokenfactory module

### PR DESCRIPTION
**Pull request by niilptr**
## What is the purpose of the change
This change adds flowcharts images for tokenfactory module documentation of message server functions:
- ChangeAdmin
- CreateDenom
- Burn
- Mint
- SetDenomMetadata
## Documentation and Release Note
  - [ ] Does this pull request introduce a new feature or user-facing behavior changes?
  - [ ] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?
Where is the change documented?
  - [x] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [ ] N/A

### CODE REVIEW

**Review by mattverse — APPROVED** [review]
LGTM, thanks so much for this!

**Review by ValarDragon — APPROVED** [review]
This is really nice!

**Comment by alessandromazza98** [comment]
Right now we did it manually but we could develop an automated way of doing these flowcharts if you are interested.

**Comment by 0xstepit** [comment]
I agree with you that having good documentation is crucial in open source software and for onboarding new developers. We have initiated internal discussions regarding a possible implementation.

**Pull request merged**
