### PR TITLE
Whitelist EstimateSwapExactAmountOut

### PR DESCRIPTION
**Pull request by frostornge**
## What is the purpose of the change

This PR allows WASM contracts to estimate the swap input amount if the output amount is determined.

## Brief Changelog

- adds `/osmosis.gamm.v1beta1.Query/EstimateSwapExactAmountOut` query message to whitelist and registers its response with `&gammtypes.QuerySwapExactAmountOutResponse{}`

## Testing and Verifying

--- needs e2e test via live contract

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (yes / no)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (yes / no)
  - How is the feature or change documented? (not applicable   /   specification (`x/<module>/spec/`)  /  [Osmosis docs repo](https://github.com/osmosis-labs/docs)   /   not documented)

### CODE REVIEW

**Comment by ValarDragon** [comment]
LGTM, can you add a changelog entry?

**Comment by frostornge** [comment]
> LGTM, can you add a changelog entry?

Yeah sure! will do

**Comment by frostornge** [comment]
Done :)

**Review by ValarDragon — APPROVED** [review]

**Review by mattverse — APPROVED** [review]
LGTM 🌮 !

**Pull request merged**
