### PR TITLE
Add distribution event

### PR DESCRIPTION
**Pull request by antstalepresh**

### CODE REVIEW

**Review by ValarDragon — APPROVED** [review]

**Comment by robert-zaremba** [comment]
Why not using proto events? Much better DevUX. You create a proto type for event and push it, instead of creating dynamic attributes.

**Comment by sunnya97** [comment]
@robert-zaremba are proto events ready to use? Do you have an example code of how to use them?

**Comment by robert-zaremba** [comment]
> are proto events ready to use?

Yes, although the type is set to the proto type (so it's long). 

> Do you have an example code of how to use them?

+ https://github.com/cosmos/cosmos-sdk/blob/master/proto/cosmos/authz/v1beta1/event.proto
+ https://github.com/cosmos/cosmos-sdk/blob/master/x/authz/keeper/keeper.go#L144

**Comment by sunnya97** [comment]
@ValarDragon wdyt of switching to these ^

**Comment by ValarDragon** [comment]
These are great! I had just thought that they were blocked on sdk v0.43.0

**Pull request merged**
