### PR TITLE
Add seed dual.systems node init.go

### PR DESCRIPTION
**Pull request by dualsystems**

### CODE REVIEW

**Comment by faddat** [comment]
thank you.

**Review by ValarDragon — APPROVED** [review]
LGTM

**Comment by ValarDragon** [comment]
Wait, question: Do you folks run a validator / other Osmosis infra

**Comment by ValarDragon** [comment]
Yeah agreed. I think we do unfortunately have to maintain some whitelisting here. I'm personally down for any chain validators with reputation somewhere in the cosmos community being able to add seeds in

**Comment by dualsystems** [comment]
Hello, I validator in other cosmos chains and have running osmosis node. Seed node is not obliged to be a validator. 
But I also consider this list requires attention, I have a desire to start the seed server for few chains in cosmos ecosystem.

**Comment by faddat** [comment]
Which chains, could you pls provide links?

thanks

**Comment by ValarDragon** [comment]
Closing for now, please re-open if you have availability to provide more context!

**Pull request closed without merging**
