### PR TITLE
Added go mod download github.com/avast/retry-go

### PR DESCRIPTION
**Pull request by lightiv**
This was required before I was able to build the new binary.

Closes: #XXX

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by lightiv** [comment]
Look like this is only need if go version is not v1.17.1

**Comment by lightiv** [comment]
Probable should just have users check go version before starting the instructions.  Thanks.

**Comment by ValarDragon** [comment]
We really want people to be using `go 1.17`. I'm actually shocked that the compiler doesn't fail to compile on go 1.16. Several of the dependencies depend on `go 1.17`, and I don't really know if/how they depend on go 1.17 features.

I'm pretty hesistant to merge this.

**Comment by lightiv** [comment]
I agree, you should just make step 1 be to ensure Go v1.17.x is installed.

**Pull request closed without merging**
