### PR TITLE
chore: remove concurrency from go-client

### PR DESCRIPTION
**Pull request by p0mvn**
Closes: #XXX

## What is the purpose of the change

Remove broken concurrency from go-client

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? no
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? no
  - How is the feature or change documented? not applicable

### CODE REVIEW

**Comment by jonator** [comment]
Checkout:
https://github.com/osmosis-labs/osmosis/pull/4859

I got concurrency to work, except for account sequence mismatch errors

**Review by jonator — COMMENTED** [review]
Hmm somehow without concurrency I get a similar segfault:

```
~/Dev/osmosis (roman/remove-concurrency-script) » make localnet-cl-create-positions                                                                                                                                         2 ↵ jonator@jonsmac
go run tests/cl-go-client/main.go
2023/04/07 09:07:25 connected to:  chain-id localosmosis height 3211
2023/04/07 09:07:25 -1620   3420
2023/04/07 09:07:25 creating position: pool id 1 accountName lo-test2 lowerTick -1014 upperTick 2841 token0Desired 35010051uosmo tokenDesired1 87113937uion defaultMinAmount 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x38 pc=0x10146cfac]

goroutine 1 [running]:
github.com/ignite/cli/ignite/pkg/cosmosaccount.Account.Address({{0x0?, 0x15?}, {0x0?, 0x0?}}, {0x1019d598c, 0x4})
        /Users/jonator/go/pkg/mod/github.com/p0mvn/cli@v0.23.1/ignite/pkg/cosmosaccount/cosmosaccount.go:136 +0x2c
main.getAccountAddressFromKeyring({0x140011bb3b0, {{0x1020b7bd0, 0x140001e5c00}, {0x1020b3380, 0x140001e5c40}, {0x1020ad1d8, 0x102b8a510}, 0x0, 0x0, 0x493e0, ...}, ...}, ...)
        /Users/jonator/Dev/osmosis/tests/cl-go-client/main.go:167 +0x138
main.createPosition({0x140011bb3b0, {{0x1020b7bd0, 0x140001e5c00}, {0x1020b3380, 0x140001e5c40}, {0x1020ad1d8, 0x102b8a510}, 0x0, 0x0, 0x493e0, ...}, ...}, ...)
        /Users/jonator/Dev/osmosis/tests/cl-go-client/main.go:142 +0x8c
main.main()
        /Users/jonator/Dev/osmosis/tests/cl-go-client/main.go:108 +0xa10
exit status 2
make: *** [localnet-cl-create-positions] Error 1
```

**Comment by p0mvn** [comment]
Yeah, I saw the change, thank you.

While it's awesome that the seg fault is solved, I don't think this account sequence is easily solvable. So far this concurrency change has only been an impediment. I think it was merged without testing. 

So I think it would be most productive to remove it since everyone has been having issues with the account sequence, and just add positions synchronously

**Comment by p0mvn** [comment]
> Hmm somehow without concurrency I get a similar segfault:
> 
> ```
> ~/Dev/osmosis (roman/remove-concurrency-script) » make localnet-cl-create-positions                                                                                                                                         2 ↵ jonator@jonsmac
> go run tests/cl-go-client/main.go
> 2023/04/07 09:07:25 connected to:  chain-id localosmosis height 3211
> 2023/04/07 09:07:25 -1620   3420
> 2023/04/07 09:07:25 creating position: pool id 1 accountName lo-test2 lowerTick -1014 upperTick 2841 token0Desired 35010051uosmo tokenDesired1 87113937uion defaultMinAmount 0
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x2 addr=0x38 pc=0x10146cfac]
> 
> goroutine 1 [running]:
> github.com/ignite/cli/ignite/pkg/cosmosaccount.Account.Address({{0x0?, 0x15?}, {0x0?, 0x0?}}, {0x1019d598c, 0x4})
>         /Users/jonator/go/pkg/mod/github.com/p0mvn/cli@v0.23.1/ignite/pkg/cosmosaccount/cosmosaccount.go:136 +0x2c
> main.getAccountAddressFromKeyring({0x140011bb3b0, {{0x1020b7bd0, 0x140001e5c00}, {0x1020b3380, 0x140001e5c40}, {0x1020ad1d8, 0x102b8a510}, 0x0, 0x0, 0x493e0, ...}, ...}, ...)
>         /Users/jonator/Dev/osmosis/tests/cl-go-client/main.go:167 +0x138
> main.createPosition({0x140011bb3b0, {{0x1020b7bd0, 0x140001e5c00}, {0x1020b3380, 0x140001e5c40}, {0x1020ad1d8, 0x102b8a510}, 0x0, 0x0, 0x493e0, ...}, ...}, ...)
>         /Users/jonator/Dev/osmosis/tests/cl-go-client/main.go:142 +0x8c
> main.main()
>         /Users/jonator/Dev/osmosis/tests/cl-go-client/main.go:108 +0xa10
> exit status 2
> make: *** [localnet-cl-create-positions] Error 1
> ```

Let's merge that change then if it works. Maybe there is a platform-specific problem requiring the mutex

**Comment by p0mvn** [comment]
@jonator merged #4859  here, can you try again please?

**Review by jonator — APPROVED** [review]
Slow, but more reliable 👍 > 🚴‍♂️

**Pull request merged**
