### PR TITLE
dev-ux: fix branch name in gosec workflow

### PR DESCRIPTION
**Pull request by pysel**
Closes: #XXX

## What is the purpose of the change

[GoSec action](https://github.com/osmosis-labs/osmosis/blob/main/.github/workflows/gosec.yml) has incorrect [branch names](https://github.com/osmosis-labs/osmosis/blob/main/.github/workflows/gosec.yml#L5) in events that trigger the workflow field. It has only ran [once](https://github.com/osmosis-labs/osmosis/actions/workflows/gosec.yml). This PR changes the branch names used in the workflow.

NOTE: this PR does not test wether the action works correctly, it only fixes branch names

## Testing and Verifying

See "NOTE"

Where is the change documented? 
  - [x] N/A

### CODE REVIEW

**Comment by pysel** [comment]
oh wow, there are a lot of [errors](https://github.com/osmosis-labs/osmosis/actions/runs/6083517025/job/16503535349?pr=6312) reported by gosec

**Review by ValarDragon — APPROVED** [review]

**Comment by mattverse** [comment]
@ValarDragon What's the tradeoff for having go-sec? CI time?

**Comment by p0mvn** [comment]
@pysel could you apply ValarDragon's suggestion please?

I suggest linking this PR in the comment for context as well

**Comment by pysel** [comment]
I changed the workflow do trigger manually for now, I think it is the best course of action for now

**Comment by p0mvn** [comment]
> I changed the workflow to trigger manually for now, I think it is the best course of action for now

Awesome! Thank you

**Review by p0mvn — APPROVED** [review]
LGTM

**Pull request merged**
