### PR TITLE
add auth.moduleaccounts to the stargate whitelist

### PR DESCRIPTION
**Pull request by ibjc**
Closes: #6585

## What is the purpose of the change

this PR will enable smart contracts to fetch osmosis's module accounts.

## Testing and Verifying

This change is a trivial rework / code cleanup without any test coverage.

* that said, let us know if this code change is not considered trivial *

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes?
  - [x] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented? 
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [ x] N/A

### CODE REVIEW

**Comment by mattverse** [comment]
devbot help

**Comment by devbot-wizard** [comment]
Hi! I'm DevBot, a bot that helps with common tasks in the development process. Commands:
- `devbot fix`: Fix basic errors in the PR. (e.g. imports, changelog conflicts, go mod conflicts)
- `devbot merge base`: Merge the base branch into the PR branch.
- `devbot add changelog [misc/feat/bug/api/sec] [message]`: Add a changelog entry to the PR. (e.g. `devbot add changelog feat Added a new feature`)
    - If message is blank, defaults to PR title.
- `devbot re-pr`: Re-PR the PR, useful for external contributors where we have no edit perms.

**Comment by mattverse** [comment]
devbot add changelog misc add (x/auth) ModuleAccounts query to stargate whitelist

**Review by mattverse — APPROVED** [review]
This query already present in osmosis std, lgtm

**Comment by mattverse** [comment]
devbot add changelog misc add x/auth: ModuleAccounts query to stargate whitelist

**Comment by mattverse** [comment]
@ibjc Would you be able to add a changelog for this? Thanks!

**Comment by ibjc** [comment]
> @ibjc Would you be able to add a changelog for this? Thanks!

oh sure thing, will do

**Pull request merged**
