### PR TITLE
Update twap response

### PR DESCRIPTION
**Pull request by hieuvubk**
Closes: #2622

## What is the purpose of the change

> Add a bool field for "is response unstable" to the twap queries

## Brief Changelog

*(for example:)*
 
  - *Update proto*
  - *Check the err in the queries to return the appropriate response*
  - *Add tests*

### CODE REVIEW

**Review by mattverse — COMMENTED** [review]
Oh i see the `is_response_unstable` fields is for when the twap query fails.

Don't know how others feel about this, but my suggestion would be changing the field name from `is_response_unstable` to `success`

**Comment by hieuvubk** [comment]
> Oh i see the `is_response_unstable` fields is for when the twap query fails.
> 
> Don't know how others feel about this, but my suggestion would be changing the field name from `is_response_unstable` to `success`

need to change some logic but yess

**Comment by mattverse** [comment]
@hieuvubk  Can you look into proto gen ( if it's correctly updated) before we merge this? (Upon seeing check proto CI failing)

**Comment by hieuvubk** [comment]
> @hieuvubk Can you look into proto gen ( if it's correctly updated) before we merge this? (Upon seeing check proto CI failing)

I already ran both `make proto-all` & `make proto-gen` but it still happen. Seem we got this CI err before.

**Comment by mattverse** [comment]
@hieuvubk interesting, can you try merging with current main on ur branch and then running it?

**Comment by hieuvubk** [comment]
> @hieuvubk interesting, can you try merging with current main on ur branch and then running it?

Still got the `check-proto` err

**Comment by faddat** [comment]
trying a quick `make proto-all` here

**Comment by faddat** [comment]
hey @hieuvubk -- I suspect that you may have found a bug with this one. 

Like you, when I try it, I end up in the same spot that you did.

**Pull request closed without merging**
