### PR TITLE
Mergify: first configuration commit

### PR DESCRIPTION
**Pull request by daniel-farina**
Adding the first configuration for Mergify
Ideally, I would this to be reviewed by people who had previous experience with mergify.

Closes: #511

### CODE REVIEW

**Review by ValarDragon — APPROVED** [review]
LGTM! I'm down to just merge it and try it out

**Comment by ValarDragon** [comment]
If this works, perhaps we try switching the commit message template to whats in the latest SDK?

https://github.com/cosmos/cosmos-sdk/blob/master/.mergify.yml#L16-L18

**Comment by ValarDragon** [comment]
Do we need to make the backport labels, or does the bot do that?

**Comment by daniel-farina** [comment]
This was closed in favor of https://github.com/osmosis-labs/osmosis/pull/847.

**Pull request closed without merging**
