### PR TITLE
create global swap default swap and exit fees

### PR DESCRIPTION
**Pull request by sunnya97**
Closes: #XXX

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by ValarDragon** [comment]
Hrmm, not sure I agree that we should restrict things to one swap fee. Its a pretty clear trade-off for tail-end things / things with less fungibility, you want higher swap fees. We also want more flexibility to change things to lower swap fees imo.

I'm fine with restricting to some presets / not giving the full range of motion, but I don't think restricting to one is a good move

I'm fine with just removing exit fee though tbh

**Comment by sunnya97** [comment]
Yeah, governance should be able to change swap fees on pools.  This just sets the default for the permissionless creation of new pools

**Comment by faddat** [comment]
I think this makes sense.  Can users override this default?

**Comment by ValarDragon** [comment]
Going to close this for now. Lets revisit a design that fits the desired needs.

**Pull request closed without merging**
