### PR TITLE
Bump max gas wanted per tx to 60 mil

### PR DESCRIPTION
**Pull request by mattverse**
Closes: #XXX

## What is the purpose of the change
Bumps max gas wanted per tx default to 6 million. 

This would resolve all the issues projects were having when they were uploading contracts. 

## Testing and Verifying

This change is a trivial rework / code cleanup without any test coverage.

## Documentation and Release Note

  - [ ] Does this pull request introduce a new feature or user-facing behavior changes?
  - [ ] Changelog entry added to `Unreleased` section of `CHANGELOG.md`?

Where is the change documented?
  - [ ] Specification (`x/{module}/README.md`)
  - [ ] Osmosis documentation site
  - [ ] Code comments?
  - [ ] N/A

## Summary by CodeRabbit

- **Performance Improvements**
	- Increased the maximum gas limit per transaction to enhance transaction processing capabilities.

### CODE REVIEW

**Comment by czarcas7ic** [comment]
I think we will need to add this to the config.toml overwrite flow to make this useful

**Comment by mattverse** [comment]
@czarcas7ic this original config was in app.toml, are you suggesting we move this to config.toml?

**Comment by czarcas7ic** [comment]
Sorry I meant app.toml overwrite flow, there are two overwrite flows, one for each toml

**Review by PaddyMc — APPROVED** [review]
:+1:

**Review by ValarDragon — APPROVED** [review]

**Comment by czarcas7ic** [comment]
Because as far as I understand, this just makes it the default for when someone re initializes their configs, and that very very rarely occurs for validators.

**Comment by mattverse** [comment]
@czarcas7ic gotcha, good catch! added as requested

**Comment by czarcas7ic** [comment]
While reviewing I realized we still had the same logic for app.toml override where we check if the value is the old value and then overrides (we now just override no matter what, and the node operator can provide the flag that prevents the override if they want to use their own values.

**Pull request merged**
