### PR TITLE
x/gamm: Delete IsActive and related checks

### PR DESCRIPTION
**Pull request by AlpinYukseloglu**
Closes: #1904 

## What is the purpose of the change

Delete `IsActive` and related checks/functions.

## Brief Changelog

- Delete `IsActive` and related checks/functions

## Testing and Verifying

This change is a trivial rework / code cleanup without any test coverage.

## Documentation and Release Note

  - Does this pull request introduce a new feature or user-facing behavior changes? (no)
  - Is a relevant changelog entry added to the `Unreleased` section in `CHANGELOG.md`? (no)
  - How is the feature or change documented? (not applicable)

### CODE REVIEW

**Comment by AlpinYukseloglu** [comment]
cc: @ValarDragon since this touches checks in core swap functions

**Review by p0mvn — APPROVED** [review]
LGTM

**Comment by ValarDragon** [comment]
I'm pretty conflicted on this, I feel like this is useful for an easy thing we could just flip in the event of an emergency

**Comment by AlpinYukseloglu** [comment]
> I'm pretty conflicted on this, I feel like this is useful for an easy thing we could just flip in the event of an emergency

Hmm as in having the ability to globally freeze swaps? I honestly agree – it might be useful as a defacto chain freeze if there is an issue that is purely swap-related. Can you foresee there being any other use for it in the future, or is this pretty much what we would be keeping it for?

**Comment by AlpinYukseloglu** [comment]
Decided on call to add a comment explaining intended use (emergency switch for all pools/individual pools) + a test that showcases this behavior

**Comment by mattverse** [comment]
Changing this temporarily to draft to avoid accidental merging!

**Comment by AlpinYukseloglu** [comment]
This PR is currently blocked on this question: https://github.com/osmosis-labs/osmosis/issues/1904#issuecomment-1173996815

**Comment by AlpinYukseloglu** [comment]
Decided in the related issue to keep `IsActive`, so I'm closing this PR in favor of a separate testing-related one

**Pull request closed without merging**
