### PR TITLE
Merge `concentrated-liquidity-main` `x/concentrated-liquidity` with history preserved, no state-breaks

### PR DESCRIPTION
**Pull request by p0mvn**
Closes: #XXX

## What is the purpose of the change

This PR merges all contents of the new `x/concentrated-liquidity` module that was developed on the `concentrated-liquidity-main` branch while preserving the commit history.

Once approved, it should be merged non-squashed.

## Brief Changelog

- Merge `x/concentrated-liquidity` and `proto/osmosis/concentrated-liquidity` folders from `concentrated-liquidity-main`
- Remove all state breaks and resolve build issues by unwiring the module, commenting out codec changes and disabling dependent tests. This was done in: https://github.com/osmosis-labs/osmosis/pull/3877` See that PR for details. All removed logic is tracked here: https://github.com/osmosis-labs/osmosis/issues/3556#issuecomment-1366847286

The module will be wired up and tests re-enabled in: https://github.com/osmosis-labs/osmosis/pull/3876

### CODE REVIEW

**Comment by p0mvn** [comment]
Note: every TODO, test skip, codec, and module unwiring has been isolated in the latest commit made to this branch from a PR:
https://github.com/osmosis-labs/osmosis/pull/3877

This was done to avoid state-breaks while resolving all build issues and CI test failures.

Please review #3877 to understand each TODO in more detail.

All of the TODOs are tracked here: https://github.com/osmosis-labs/osmosis/issues/3556#issuecomment-1366847286

**Review by p0mvn — COMMENTED** [review]
This LGTM. Re-confirmed that no state-breaks happen.

PLEASE DO NOT SQUASH MERGE. This needs to be merged with commit history preserved.

**Review by czarcas7ic — APPROVED** [review]
The only issues I see have been fixed in subsequent PRs that are currently pointed to cl-main and can be redirected to main once this PR is merged.

**Review by ValarDragon — APPROVED** [review]
Reviewed that this has no state break!

Did not review any of the logic, leaving that for a later at-end review. Doing rebase + merge

**Pull request merged**
