### PR TITLE
chore(x/protorev): use `errors.New` to replace `fmt.Errorf` with no parameters

### PR DESCRIPTION
**Pull request by yukionfire**
`errors.New` is specifically designed to instantiate a new error with a given message, without any formatting overhead. I think this should be the preferred method when we do not need to format the error string.

On the other hand, it saves a couple function calls and a comparison on the error path, although this is tiny diff...

### CODE REVIEW

**Comment by czarcas7ic** [comment]
Please open a single PR with the desired changes

**Comment by yukionfire** [comment]
> Please open a single PR with the desired changes

Sorry for this, I thought that would changes too much files in one pr, so I splitted them into 3 prs.

I just chery pick other prs' commits to this pr, thanks for your review

**Review by p0mvn — APPROVED** [review]

**Comment by PaddyMc** [comment]
Would you mind updating the PR description to something meaningful?

Would like to know your thought process behind this change before merging?

**Comment by yukionfire** [comment]
@PaddyMc updated, thx sir.

**Review by ValarDragon — APPROVED** [review]

**Comment by PaddyMc** [comment]
Can you fix the tests please? :pray:

**Comment by yukionfire** [comment]
> Can you fix the tests please? :pray: 
@PaddyMc Hi sir, I have fixed the tests. The new ci errors seems that not relevent to this PR, or shall I fix them too?

**Comment by PaddyMc** [comment]
> Hi sir, I have fixed the tests. The new ci errors seems that not relevent to this PR, or shall I fix them too?

Thanks for fixing the tests. 

These error are because you've created a PR from a fork and are known errors, I can run the e2e tests locally then I'll merge, thanks for this PR :bow:

**Pull request merged**
