### PR TITLE
Get initial test for showing that reward distribution works

### PR DESCRIPTION
**Pull request by ValarDragon**
## Description

Going to work on exact number calculations in a second PR, but wanted to get this up just to get the infra up for others.

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/gaia/blob/main/CONTRIBUTING.md#pr-targeting))
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

**Comment by mattverse** [comment]
@ValarDragon what's the status of this PR? Are you planning to continue? I can also take over!

**Comment by ValarDragon** [comment]
I think this is going to be significantly easier to rewrite with #1008

**Comment by mattverse** [comment]
agreed, lets try pushing forward https://github.com/osmosis-labs/osmosis/pull/1008 and then revisit this

**Comment by ValarDragon** [comment]
yeah, no need to even get this PR merged, at most look at it for inspiration imo

**Comment by mattverse** [comment]
Closing this PR in favor of https://github.com/osmosis-labs/osmosis/pull/1070

**Pull request closed without merging**
